### ISSUE TITLE
Radio buttons don't support boolean values

### ISSUE THREAD

**Issue by uzquiano** [gitana/alpaca#1]
It should be possible to have radio buttons that support any kind of value - not just strings.

Here is a case with booleans that fails:

schema -
                       "smtpEnabled": {
                           "type": "boolean",
                           "helper": "Please select whether or not you would like your email to have SMTP enabled.",
                           "enum": [true, false],
                           "default": true,
                           "required": true
                       },

options -
                       "smtpEnabled": {
                           "label": "Email SMTP Enabled",
                           "type": "radio",
                           "optionLabels": ["True", "False"]
                       }

When we draw back the value of the control, we get a JSON object that has { "smtpEnabled": "true" }.  It should be { "smtpEnabled": true }.

**Comment by jellomold** [comment]
In 1.5.27 this issue has returned. Radio buttons don't support boolean values. 
strings and integers work fine.
