### ISSUE TITLE
Styling and Labels Not Rendering

### ISSUE THREAD

**Issue by groogiam** [gitana/alpaca#108]
I am trying out alpaca with r&d project I am working on. When I attempt to render a simple form no labels, descriptions or styles are rendered I have attached an image of what my rendered form looks like. Below is the calling code, schema and options files I am using as well as the script and css includes. Any help you can provide will be much appreciated. Thanks.

var alpacaData = {
            "data": viewModel.ResourceWithFocus.ResourceData.toJSON(),
            "schemaSource": window.AppPath + "/" + viewModel.ResourceWithFocus.SchemaSource,
            "optionsSource": window.AppPath + "/" + viewModel.ResourceWithFocus.OptionsSource,
            "postRender": function (form) { viewModel.NonSerialized.AlpacaForms[viewModel.ResourceWithFocus.ResourcePath] = form; }
        };
        $("#resourceEditForm").alpaca(alpacaData);

/\* ------------------- options.json ------------------------*/

{
  "fields": {
    "Description": {
      "type": "textarea"
    },
    "ModelNodePath": {
      "type": "hidden"
    },
    "EntityType": {
      "type": "hidden"
    },
    "NodeEntityType": {
      "type": "hidden"
    }
  }
}

/\* -------------------------------- schema.json --------------------------------- */
{
  "title": "Business Domain Definition",
  "description": "Business Domain Details Form",
  "type": "object",
  "properties": {
    "DisplayName": {
      "title": "Display Name",
      "description": "Display name of the application. This is what users will see in the user interface.",  
      "required": true,
      "type": "string"
    },
    "Description": {
      "title": "Description", 
      "description": "Description of the business domain. The description will be displayed as a tool tip when the business domain is hovered over.", 
      "type": "string"
    },
    "ModelNodePath": {
      "required": true,
      "type": "string"
    },
    "EntityType": {
      "required": true,
      "type": "string"
    },
    "NodeEntityType": {
      "required": true,
      "type": "string"
    }
  }
}

/\* ------------------------- Css and script includes ------------ */

```
<script src="@Url.Content("~/Scripts/kendo/jquery.min.js")"></script>
<script src="@Url.Content("~/Scripts/kendo/kendo.all.min.js")"></script>
<script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")"></script>
<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
<script src="@Url.Content("~/Scripts/JQueryUi/jquery-ui.min.js")"></script>
<script src="@Url.Content("~/Scripts/alpacajs/js/alpaca.min.js")"></script>
<script src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"></script>

<link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/grids-min.css")" rel="stylesheet" type="text/css" />

<link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/kendo/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content(CustomHtmlHelpers.KendoUiStyleCssRelativePath)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/kendo/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Scripts/alpacajs/css/alpaca.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Scripts/alpacajs/css/alpaca-jqueryui.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Scripts/JQueryUi/css/ui-lightness/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
```

![alpacaissue](https://f.cloud.github.com/assets/1992395/2123118/cc36a7aa-9224-11e3-94eb-52f81a1f6df0.JPG)

**Comment by carlos22** [comment]
How did you solve the problem? I have a similar issue.
