### ISSUE TITLE
Rude versioning

### ISSUE THREAD

**Issue by ftrotter** [gitana/alpaca#117]
I have some relatively complex forms that were working with previous versions of alpaca. 

Now they stopped working. 

I would like to test and see if the new version of alpaca is the problem, but I cannot do that, because I cannot find a way to get to older known-good versions. I do not want to sort out how you build your project from github.

If you are recommending versionless CDN integration, and you are making breaking changes to that CDN instance (intentionally or not) then you really need to give people access to the old versions of the code for debugging purposes. 

Could you please provide links to previous versions of the library in your downloads section so that I could conveniently rule out Alpaca version issues as part of my debugging process? There is a reason that JQuery and other in-development libraries do this.

-FT

**Comment by uzquiano** [comment]
Closing since this is a year old.  If anyone is on 1.1.x, advise to upgrade to 1.5 and follow the commit log.  If assistance is needed, please contact us via the contact us page (http://www.alpacajs.org) for consulting assistance.
