### ISSUE TITLE
Custom Button with Click Event

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#136]
Dear Team,

Is there any facility for adding button click event ?

Regards,
Hardik Kaji

**Comment by DerekOverlock** [comment]
Is this button.class option functioning? I just tried it with the latest version of Alpaca and it seems to not take the option. Here's is the form field in my options field.
```
	           "form" : {
	             "method" : "POST",
	             "action" : "",
	             "buttons" : {
		             "button" : {
		                 "class" : "btn-primary",
		                 "title" : "Save Response"
		             }  
		           }
	           }
```

**Comment by billbarsch** [comment]
I need to change the btn-default to btn-primary on submit button class
please create this option: (postrender is not a good solution)

  "form" : {
                 "method" : "POST",
                 "action" : "",
                 "buttons" : {
                     "button" : {
                         "class" : "btn-primary",
                         "title" : "Save Response"
                     }  
                   }
               }

**Comment by Avtonom** [comment]
@yaworsw Is it possible to use the wizard steps?

**Comment by Troy-Yang** [comment]
Actually we can drop off the form buttons and add any custom buttons any where. 

The solution include two steps: 1. create an alpaca element(container). 2. create a custom button anywhere you want and bind a click event, in the click event, we can collect all the data from alpaca element.

For example:
`
$("#markupconfiguration-form-content-alpaca").alpaca("destroy");
        $("#markupconfiguration-form-content-alpaca").alpaca({
             "data": {...},
             "schema": {...}
});

function save(){
         var value = $("#markupconfiguration-form-content-alpaca").alpaca().getValue();
}
`

The key is we collect the values not from the alpaca form build-in button or postRenderCallback

**Comment by veso266** [comment]
@DerekOverlock
not sure if you still need it but use styles instead of class
```json
"form" : {
                 "method" : "POST",
                 "action" : "",
                 "buttons" : {
                     "button" : {
                         "styles" : "btn btn-primary",
                         "title" : "Save Response"
                     }  
                   }
               }
```
