### ISSUE TITLE
Datetime Field is not working

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#138]
Dear Team,

I've checked your online demo of DateTime field its not working online.
http://www.alpacajs.org/examples/components/fields/datetime-field.html#examples

I have tried same demo on my machine. that is also not working.

Please look into issue.

Thanks in advance.

Regards,
HaRdik Kaji

**Comment by mjijas** [comment]
hardikkaji  can u plz shr the alpaca date time picker code with me

**Comment by hardikkaji** [comment]
@mjijas i have used same code which is on alpaca.js [documentation](http://www.alpacajs.org/docs/fields/datetime.html). Please refer same code below.

```
$("#field1").alpaca({
    "schema": {
        "format": "datetime"
    }
});
```

**Comment by rsdjulfakar** [comment]
If all the dependencies are in place; Just add below css in your code and that's it:

    .bootstrap-datetimepicker-widget.dropdown-menu {
        display: block !important;
    }


This issue occurs due to the below display css in dropdowns.less css of Bootstrap:

    .dropdown-menu {
      position: absolute;
      top: 100%;
      left: 0;
      z-index: @zindex-dropdown;
      display: none; // none by default, but block on "open" of the menu
      float: left;
      min-width: 160px;
      padding: 5px 0;
      margin: 2px 0 0; // override default ul
      list-style: none;
      font-size: @font-size-base;
      text-align: left; // Ensures proper alignment if parent has it changed (e.g., modal footer)
      background-color: @dropdown-bg;
      border: 1px solid @dropdown-fallback-border; // IE8 fallback
      border: 1px solid @dropdown-border;
      border-radius: @border-radius-base;
      .box-shadow(0 6px 12px rgba(0,0,0,.175));
      background-clip: padding-box;
    
     Deprecated as of 3.1.0 in favor of `.dropdown-menu-[dir]`
      &.pull-right {
        right: 0;
        left: auto;
      }
    
      // Dividers (basically an hr) within the dropdown
      .divider {
        .nav-divider(@dropdown-divider-bg);
      }
    
      // Links within the dropdown menu
      > li > a {
        display: block;
        padding: 3px 20px;
        clear: both;
        font-weight: normal;
        line-height: @line-height-base;
        color: @dropdown-link-color;
        white-space: nowrap; // prevent links from randomly breaking onto new lines
      }
    }
