### ISSUE TITLE
Custom validation message for Pattern

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#146]
Dear Team, 

I have assigned pattern to Text Box ^[A-Za-z ]+$

Its working fine.
Its showing predefined message.
`This is not a Valid pattern ^[A-Za-z ]+$`

My Requirement is that custom message in case of failure for above validation(any pattern validation).!

Regards,

**Comment by PiQ99** [comment]
Hey,

I would like to know: How is it possible to add a custom validation-message? :) Or is there also a way to deactivate this hint and just present the actual description to the form?

Thanks in advance

**Comment by hardikkaji** [comment]
@PiQ99 : You can define callbacks. Using that callbacks you can provide custom message. I have used that only. For more information use below page:

http://www.alpacajs.org/docs/api/validation.html

**Comment by jonesinator** [comment]
I had this same issue, and figured out that it can be accomplished with the following `view` json:

```
{
  "view": {
    "fields": {
      "/field1": {
        "messages": {
          "invalidEmail": "some other message"
        }
      },
      "/field2": {
        "messages": {
          "invalidValueOfEnum": "some other message"
        }
      }
    }
  }
}
```

There are many messages that can be overridden. A list of them can be found in `view.messages` of any element though the browser's developer tools.

**Comment by elricho** [comment]
@jonesinator Awesome tip ! Thanks so much.
