### ISSUE TITLE
Validator not working

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#148]
Dear Team,

I have tried Validator using below code as example in below link but it is not working.
I am using bootstrap design.

http://www.alpacajs.org/examples/components/validation/validation-examples.html

```
"validator":function(control, callback) {
                    console.log("called");
                    if (control.getValue()['age'] > 18) {
                        callback({
                            "message": "Age must be less than 18.",
                            "status": false
                        });
                    } else {
                        callback({
                            "message": "Valid value (custom validator)",
                            "status": true
                        });
                    }
                }
```

console.log is displayed it goes in condition also but validation is displaying.!
Please check my code on jsfiddle

http://jsfiddle.net/2YQhv/13/

Regards,

**Comment by arthurportas** [comment]
Hi,

rewrote you scenario with 1.5.7 build and works as expected.
Check http://codepen.io/arthurportas/pen/jEvwqL
This issue should be closed.

Cheers,

**Comment by uzquiano** [comment]
Awesome! Thanks for that! Will close, please reopen if anything goes sideways.
