### ISSUE TITLE
ReRender Form

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#149]
Dear Team,

Is there any method that will re-render alpaca form?

Regards,

**Comment by arthurportas** [comment]
Hi guys,

how can in call  refresh() to my form for example on an jquery ajax request done callback ?
When i perform an ajax request for example an update, this can fail silently on server-side and it returns the same values for the model(datasource). I would like to signal alpaca that datasource might have changed and have form view refreshed.
Is this possible within 1.5.6 version?
Thanks

**Comment by uzquiano** [comment]
This seems reasonable.  

From the form, you can access form.topControl and then call form.topControl.refresh(callback).

For a more detailed response, can you write up a sample case (using jsFiddle or the like) to show how your code works?  Give it a shot and if you run into an issue, paste in the link the fiddle and we can take a look.  Certainly seems like it should work.

**Comment by arthurportas** [comment]
Hi,
form.topControl.refresh worked like a charm! Thanks for helping!
Cheers,

**Comment by uzquiano** [comment]
Glad to hear.  Closing the issue.

**Comment by neilyoung** [comment]
Is there a way to call "refresh" like so $('#form >form').refresh() ?
Getting refresh is not a function
