### ISSUE TITLE
autocomplete attribute

### ISSUE THREAD

**Issue by IL55** [gitana/alpaca#156]
Hi, here is useful attribute "autocomplete"
http://www.w3schools.com/tags/att_input_autocomplete.asp
which allows, for example, don't cache (by browser) passwords and credit card numbers.

I found that it could be easy added like "readonly" attribute:
https://github.com/gitana/alpaca/blob/4656851a0cec12a06cb34ca290296ea21a470167/js/Field.js#L542

i.e. something like this
```
                // autocomplete
                if (this.options.autocomplete) {
                    $(':input', this.getEl()).attr('autocomplete', this.options.autocomplete);
                }
```

and in options->fileds
you just define

`"autocomplete": "off"`

```
$(function() {
    $("#field2").alpaca({
        "data": "Mint Chocolate",
        "options": {
            "label": "Ice Cream",
            "autocomplete": "off",
            "helper": "Your favorite ice cream?",
            "size": 30,
            "placeholder": "Enter an ice cream flavor"
        },
        "schema": {
            "minLength": 3,
            "maxLength": 8
        }
    });
});
```

**Comment by arthurportas** [comment]
@IL55 @uzquiano following proposed approach i've submitted a pull-request [222](https://github.com/gitana/alpaca/pull/222).

**Comment by acorncom** [comment]
The above PR was merged a year ago, I think this issue can be closed

**Comment by uzquiano** [comment]
Great catch.  Thanks!
