### ISSUE TITLE
Boolean inside object disappears if false on serialization.

### ISSUE THREAD

**Issue by tylerperyea** [gitana/alpaca#158]
This is not necessarily a bug, but certainly wasn't expected for me. If I have a boolean set to false, and then serialize, it will ignore that field. This is a problem if the field is also explicitly required. It essentially means that it will always fail validation.

```javascript
$(function() {
    $("#field1").alpaca({
            "schema": {
	    "title":"Test",
	    "type":"object",
	    "properties":{
		"bool":{
		    "type":"boolean",
		    "required":true
		}
	    }
	}
    });
});

//If checkbox is off
JSON.stringify($("#field1").alpaca().getValue());
//output: {}


//If checkbox is on
JSON.stringify($("#field1").alpaca().getValue());
//output: {"bool":true}

//This is strange and unexpected.

```
I have made a change that fixes this in a fork. But I'm not sure if there's a deeper reason for this that I'm missing. See this commit for details:

[Forked Commit](https://github.com/tylerperyea/alpaca/commit/c9e737eeec5a341b6324e4538f85941dc7aaeea3)

**Comment by uzquiano** [comment]
Tested this in the latest 1.5.x and now works properly.
