### ISSUE TITLE
Layout for nested objects

### ISSUE THREAD

**Issue by jiexinhuang** [gitana/alpaca#169]
If in my schema I have properties that are objects, I would like to set different layout for their nested properties. Is there any way to do this in view assignment?

I found the layout template only apply to the root level, and they are not passed down.

**Comment by uzquiano** [comment]
With Alpaca 1.5.x, you can override specific field templates at any depth within the hierarchy.  Layouts are top-level down when applied to an object structure.  If you want fine-grained control, you can always implement your own views or custom field controls.

**Comment by epicfaace** [comment]
How do you apply a layout for a specific object?
