### ISSUE TITLE
A field with format is required even with "required":false

### ISSUE THREAD

**Issue by picsoung** [gitana/alpaca#171]
Hi,

I tried to use alpaca on one of my forms.

I have setup some formatting for fields to get email or URL. In the schema I defined those fields like this:

```js
"email":{
          "type":"string",
          "format" : "email",
          "title":"email",
          "required":false
        }
```

What I've found out: I can submit my form unless those fields are filed.
So having some kind of formatting makes this field "required".

Is there a way around this issue?
or it's a bug?

THanks

**Comment by uzquiano** [comment]
Tested this out in the latest 1.5.x master and it appears to work fine.  Can you give it a shot?

If this is still an issue, please re-open and share the exact form configuration you're using.  Happy to fix this if it is still an issue.
