### ISSUE TITLE
Default Field Values not working

### ISSUE THREAD

**Issue by bkempe** [gitana/alpaca#183]
Release notes for 1.1.1 mention

> Default Field Values
> Alpaca fields now handle default or unassigned values more appropriately. The JSON is effectively thinned out by removing any values that need not be expressed based on their default and required attributes."

However, when I run the code below and click the Serialize button, I still see the default value in the JSON object.

```javascript
$("#field1").alpaca({
    "schema": {
        "type": "object",
        "properties": {
            "property": {
                "type": "string",
                "default": "some default"
            }
        }
    },
    "options": {
        "form": {
            "buttons": {
                "submit": {
                    "title": "Serialize",
                    "click": function() {
                        var value = this.getValue();
                        alert(JSON.stringify(value, null, "  "));
                    }
                }
            }
        }
    }
});
```

**Comment by uzquiano** [comment]
This is correct behavior.  Perhaps the release notes were ambiguous.  A default value is a value that a property will take on if left unassigned.  So when the form renders, the value "some default" will be in it.  Serializing the form should produce a JSON object with "some default" in it.
