### ISSUE TITLE
Integer Validation on Advanced Path Trouble

### ISSUE THREAD

**Issue by hooflung64** [gitana/alpaca#186]
https://github.com/gitana/alpaca/blob/master/src/js/fields/advanced/IntegerField.js#L103

var textValue = this._getControlVal();

This will always return the actual type instead of a textValue

https://github.com/gitana/alpaca/blob/master/src/js/fields/advanced/IntegerField.js#L117

This will always throw an "Uncaught TypeError: undefined is not a function" on match if the type is a number or boolean. The basic version of this method has a valid working variation as it works directly on the input value.

https://github.com/gitana/alpaca/blob/master/src/js/Field.js#L152

This seems to be the issue as ensureProperType will always convert the type event if that is not the intention of the calling operation.

Great work so far! Alpaca is shaping up excellently.

**Comment by uzquiano** [comment]
Great.  Thanks for all the detail!

Fixed in head.  Will be pushed out shortly with the next release.
