### ISSUE TITLE
emptySelectFirst selects all radio buttons

### ISSUE THREAD

**Issue by ASchriever** [gitana/alpaca#187]
Using code from //code.cloudcms.com/alpaca/1.5.5/bootstrap/alpaca.min.js, all buttons in a Radio control are selected.  In the afterRenderControl method of Alpaca.Fields.RadioField, this code is the culprit:

$("input:radio:first", self.control).attr("checked","checked");

The expression actually selects multiple radios, because self.control is a jquery object containing more than one element.  Also, the use of attr is incorrect here.

This will fix it:

$("input:radio", self.control).eq(0).prop("checked",true);

**Comment by uzquiano** [comment]
Blimey, you're right.  Fixed in head.  Thanks for the detailed notes!
