### ISSUE TITLE
this.submitAjax() sends no data

### ISSUE THREAD

**Issue by jkernagis2** [gitana/alpaca#188]
See: https://github.com/gitana/alpaca/blob/4ba163ebcef3c8ed32426cf3cd3d7d68a94e4167/src/js/Form.js#L536

A local variable 'value' is set to this.getValue(), but it is not included in the subsequent ajax request, so no form data is actually posted when using the built in submitAjax function.  Can workaround by doing the ajax call yourself (as I am), but it would be nice if this wasn't required.

**Comment by uzquiano** [comment]
Yikes, that's pretty hideous.  Thanks for finding that.  Fixed in head and will be in the next minor release.
