### ISSUE TITLE
Incorrect message when multipleOf validation fails

### ISSUE THREAD

**Issue by ASchriever** [gitana/alpaca#189]
In version 1.5.5 I receive the message "This value is nu" when input values do not pass the multipleOf validation.  You can actually find the message in the code (see the last property below):

    Alpaca.registerMessages({
        "stringValueTooSmall": "The minimum value for this field is {0}",
        "stringValueTooLarge": "The maximum value for this field is {0}",
        "stringValueTooSmallExclusive": "Value of this field must be greater than {0}",
        "stringValueTooLargeExclusive": "Value of this field must be less than {0}",
        "stringDivisibleBy": "The value must be divisible by {0}",
        "stringNotANumber": "This value is not a number.",
        "stringValueNotMultipleOf": "This value is nu"
    });

**Comment by uzquiano** [comment]
Fixed!  Thanks, it's in head and will be in the next release!
