### ISSUE TITLE
handsontable method is not defined

### ISSUE THREAD

**Issue by yrojha4ever** [gitana/alpaca#191]
Hello team,
I am having undefined is not a function error due to this line:
$(holder).handsontable(gridConfig);

Method handsontable is not found. 

Is it possible to fix this bug?
Thanks

**Comment by uzquiano** [comment]
Does this work for you - http://www.alpacajs.org/docs/fields/grid.html?

Did you include the handsontable library?  That seems like a pretty straightforward jQuery error.  If not, can you post a jsFiddle so that we can reproduce?

**Comment by uzquiano** [comment]
Will close pending further comment.  Looks like a missed dependency library? (handsontable)
