### ISSUE TITLE
Dynamic initiation of multiple ckeditor fields fails

### ISSUE THREAD

**Issue by jflowers45** [gitana/alpaca#192]
Having an issue when I try to use multiple ckeditor fields.  I get the error that:
*"Uncaught TypeError: Cannot read property 'unselectable' of null ckeditor.js"*

The problem:
As a GIST: https://gist.github.com/jflowers45/5f26df7c6afa4fa12fd5
Hosted demo:  http://flashysubstance.com/figleaf/ckBugReport/ckBug.html

Demonstration that it works fine when not wrapping with alpaca:
As a GIST: https://gist.github.com/jflowers45/02218ea6d8214564c01e
Hosted Demo: http://flashysubstance.com/figleaf/ckBugReport/ckNoBug.html

Note that this happens in the form builder example as well.  If you go to the 'view' tab in the form builder you should have the same problem
http://www.alpacajs.org/demos/form-builder/form-builder.html

![formbuilderalpacaerror](https://cloud.githubusercontent.com/assets/1021048/5715525/30c0fae0-9aa8-11e4-893d-138eefcd4988.png)

**Comment by uzquiano** [comment]
Thanks for the detailed bug report.  This really helped.  I've taken a look and it's certainly puzzling.  Best I can work out is that it is a bug with CKEditor.  There are a number of people out there struggling with instantiation of dynamic CKEditors.  Interesting thread - (http://stackoverflow.com/questions/19328548/ckeditor-uncaught-typeerror-cannot-call-method-unselectable-of-null-in-emberj for example

I've been tinkering with your example.  Instantiating multiple CKEditors in a single Alpaca form works fine.  However, a single CKEditor in two different forms instantiated separately fails.  Appears to me to have something to do with the fireOnce() assumption of CKEditor...

No answer for this at the moment.  We may need to wait for CKEditor to address the issue.  I've tried up to 4.4.7 and still no dice.  Will play with it some more.

**Comment by jflowers45** [comment]
Thanks uzquiano.  When I was trying to figure out where CKEditor was bombing, I got pretty comfortable with the custom field definitions, so I went ahead and created one for TinyMCE and so far have had not problems dynamically instantiating them.  If there's interest let me know and can provide a demo or a pull request

**Comment by uzquiano** [comment]
That would be great!

Submit a pull request and I'll merge it in. I suspect a TinyMCE field would be quite useful to the community.

Michael

**Comment by jflowers45** [comment]
Hey Michael,
  Just submitted the pull request for TinyMCE.

https://github.com/gitana/alpaca/pull/215

**Comment by uzquiano** [comment]
A fix was introduced for CKEditor that "should" allow for better management of the destroy process.  This should help.  This works very well for us in our HTML dynamic injection front end for Cloud CMS.  I'll close this issue for now since this is about as far as we can take it unless CKEditor improves the offering.

**Comment by primac-owais** [comment]
I am getting an issue with the Object field when dragging any field up or down to the object field it is creating an duplicate object and generating an error. please suggest the possible solution for this.
