### ISSUE TITLE
Defining multiple dependencies: unexpected behavior

### ISSUE THREAD

**Issue by dyouberg** [gitana/alpaca#194]
When defining a dependency like such - the behavior is correct... When you select 'Yes', the icecream field becomes visible. 

    $("#field2").alpaca({
    "data": {},
    "schema": {
        "title": "Survey",
        "description": "Please participate in our survey",
        "type": "object",
        "properties": {
            "fan": {
                "title": "Are you an Ice Cream fanatic?",
                "type": "string",
                "enum": ["Yes", "No", "Maybe"]
            },
            "icecream": {
                "title": "I see... so what is your favorite flavor?",
                "type": "String",
                "enum": ["Vanilla", "Chocolate", "Coffee", "Strawberry", "Mint"],
                "dependencies": "fan"
            }
        }
    },
    "options": {
        "fields": {
            "fan": {
                "removeDefaultNone": true,
            },
            "icecream": {
                "dependencies": {
                    "fan": "Yes"
                }
            }
        }
    }});

However... if you want to change the dependency so that the ice cream field becomes visible on BOTH  'Yes' and 'Maybe', like this:

    "options": {
        "fields": {
            "fan": {
                "removeDefaultNone": true,
            },
            "icecream": {
                "dependencies": {
                    "fan": ["Yes", "Maybe"]
                }
            }
        }
    }

The actual behavior is opposite what I expected.  The Icecream field becomes visible only on selecting 'No' instead of 'Yes' and 'Maybe'. 

I may have made a mistake or overlooked alternative syntax, I'm still pretty new to Alpaca.  If so, please let me know!

**Comment by SuperSeb92** [comment]
This bug can be replicated simple by swapping the string to an array, e.g:


            "dependencies": {
                "fan": "Yes"
            }

will show the field when the fan field is set to "Yes"

            "dependencies": {
                "fan": ["Yes"]
            }

will show the field when fan field is ANYTHING BUT "Yes", so seems like theres some inverted logic when processing the dependencies passed as an array

**Comment by SuperSeb92** [comment]
Just so you know, I've sent a pull request with the fix here: https://github.com/SuperSeb92/alpaca/commit/fbb51cf91f2561573f96b770852ad315ebd040a9

**Comment by uzquiano** [comment]
Thanks for the PR, this was merged in.
Also added an example to the conditional dependencies documentation showing this in action.
We'll get it into the next release.
