### ISSUE TITLE
Number field required bug

### ISSUE THREAD

**Issue by ZoranPandovski** [gitana/alpaca#196]
Hi guys,
when i use field type number which contains property with minimum negative value the field is not marked as required at all, even if in it's schema required is true.
When minimum property value is positive number it works fine.I use alpaca 1.1.3

e.g.

"longitude": {
            "minimum": -180,
            "maximum": 180,
            "required": true,
            "description": "Longitude value",
            "title": "Longitude"
}

this will work 
"longitude": {
            "minimum": 0,
            "maximum": 180,
            "required": true,
            "description": "Longitude value",
            "title": "Longitude"
}

**Comment by uzquiano** [comment]
This appears to work fine in head (1.5.x branch).  I added an example to demonstrate this to the number documentation page in head to be included in the next release.

I'd recommend giving this a shot on the 1.5.x latest release and seeing if that sorts things out for you.  If not, please re-open and we can iterate as needed.
