### ISSUE TITLE
Integer value of 0 not included in form data

### ISSUE THREAD

**Issue by ASchriever** [gitana/alpaca#200]
Hi alpaca team -- thanks as always!

When the value in an integer or number field is "0", the field and the value of zero are not included in the object returned to the submitHandler by the form.getValue() call.

I've tracked the problem to the getValue method on Alpaca.Fields.ObjectField, which starts on line 18358 of the source at code.cloudcms.com/alpaca/1.5.6/bootstrap/alpaca.js.  The relevant code is at lines 18387 - 18398.  The value of a number field is evaluated as false on line 18395, so the assignedValue is never updated and therefore is never added to the object o.

I fixed this by adding a check for a number field on line 18391:

                        else if (Alpaca.isArray(fieldValue) || Alpaca.isObject(fieldValue) || Alpaca.isNumber(fieldValue))
                        {
                            assignedValue = fieldValue;
                        }

That works correctly for me and seems right, but I don't have enough knowledge of the rest of Alpaca to say for sure.

Hope this helps -- thanks again!

**Comment by uzquiano** [comment]
Awesome.  Thanks for catching that and submitting such a precise fix.  I was able to plug this in and have committed it up to head.

https://github.com/gitana/alpaca/commit/11fe5e6c65c6a91a6ae1713e93d3a3ffe42153bb

We'll have this in the next release (we're doing these monthly).
