### ISSUE TITLE
Fixes noted by community

### ISSUE THREAD

**Issue by uzquiano** [gitana/alpaca#205]
The following fixes need to be applied.  I've grouped them all together here since we want to get all of these fixed/implemented for the next release.  Not clear whether these are 1.3.x or 1.5.x.  Fixes will go into 1.5.x.

Defects related to attributes:
- [x] disallow - This schema attribute never works
- [x] disabled - This options attribute never works
- [x] readonly - This schema or options attribute doesn't work properly for Radio and date field. 
- [x] In case of Radio, When user clicks on any of the labels of options then its value changes.
- [x] In case of Date, if user clicks on date field then date picker appears and date becomes editable.
- [x] emptySelectFirst - This options attribute doesn't work properly for Radio field.
It would show all the options selected.
- [x] vertical - This options attribute doesn't work. 
Even though value of vertical is false still it shows all options vertical.
- [x] There is no way, we can have the radio options horizontal.

Already fixed in previous release:
- [x] collapsible - This options attribute works fine but with one major issue i.e.
It collapses the entire form.
- [x] Defects related to form submission.  In case of checkbox, when multiple options are selected and form is submitted, it just sends on/off values. There is no way to identify which values where selected by user.

Not a bug:
- [ ] size - This options attribute works only select field.

The size attribute appears to set fine for input, select, textarea and a few other controls.  If you look at the DOM, it is being set.  Same thing for textarea's rows and cols attributes.  They set into the DOM.  However, the size and cols attributes do not appear to do anything with the Bootstrap view since the views with Bootstrap 3.x are responsive.  Bootstrap itself seems to ignore size and cols and instead formats flexibly to the width of the viewport (media aware).

I'm not sure that this is a bug.  The DOM is being set correctly and as far as I can tell, this is correct and default responsive behavior by Bootstrap.  It's just how Bootstrap works.  If you were using a different view (such as a pure web view), the cols and size attributes would be respected.

At the moment, going to leave this as "not a bug".  Interested in feedback from the community on how this should be handled if we're not doing it properly right now?

**Comment by vikramsawant786** [comment]
Read Only for date not working properly.

$("#field2").alpaca({
    "data": "10/10/2001",
    "schema": {
        "format": "date"
    },
    "options": {
        "hideInitValidationError": false,
        "readonly":true
    }
});

**Comment by vikramsawant786** [comment]
readonly attribute for radio not working properly.
Click on the option labels then value changes.

$("#field1").alpaca({
    "data": "Coffee",
    "options": {
        "label": "Ice cream",
        "helper": "Guess my favorite ice cream?",
        "readonly":true
    },
    "schema": {
        "enum": ["Vanilla", "Chocolate", "Coffee"]
    }
});

**Comment by vikramsawant786** [comment]
emptySelectFirst not working for Radio.
$("#field1").alpaca({
    
    "options": {
        "label": "Ice cream",
        "helper": "Guess my favorite ice cream?",
        "removeDefaultNone":true,
        "emptySelectFirst ":true
    },
    "schema": {
        "enum": ["Vanilla", "Chocolate", "Coffee"]
    }
});

**Comment by vikramsawant786** [comment]
vertical attribute not working for Radio. Irrespective of value of vertical, all options are always shown vertical.
$("#field5").alpaca({
    "data": "Jimi Hendrix",
    "schema": {
        "enum": ["Jimi Hendrix", "Mark Knopfler", "Joe Satriani", "Eddie Van Halen", "Orianthi"]
    },
    "options": {
        "type": "radio",
        "label": "Who is your favorite guitarist?",
        "removeDefaultNone": true,
        "vertical": false
    }
});

**Comment by uzquiano** [comment]
Can you elaborate on:

    In case of Radio, When user clicks on any of the labels of options then its value changes.

This works this way by design.  The label wrapping of the underlying input element is by convention and a best practice within Bootstrap and other frameworks.

We render like this:

````
    <div class="radio">
        <label>
            <input type="radio" {{#if ../options.readonly}}readonly="readonly"{{/if}} name="{{../name}}" value="{{value}}" {{#compare value ../data}}checked="checked"{{/compare}}/>{{{text}}}
        </label>
    </div>
````

My understanding here may be limited.  Do you think the HTML should be different?  Is the label wrapping incorrect?  If so, what should it be?

**Comment by vikramsawant786** [comment]
disabled attribute is not working for Radio and Checkbox.

$("#field4").alpaca({
    "data": ["sandwich", "cookie", "drink"],
    "schema": {
        "type": "array",
        "enum": ["sandwich", "chips", "cookie", "drink"],
        "disabled":true
    },
    "options": {
        "type": "checkbox",
        "label": "What would you like with your order?",
        "optionLabels": ["A Sandwich", "Potato Chips", "A Cookie", "Soft Drink"]
    }
});

$("#field1").alpaca({
    "data": "Coffee",
    "options": {
        "type":"radio",
        "label": "Ice cream",
        "helper": "Guess my favorite ice cream?",
        "disabled":true
    },
    "schema": {
        "enum": ["Vanilla", "Chocolate", "Coffee"]
    }
});

**Comment by uzquiano** [comment]
I've implemented most of the fixes for the items you provided.  Can you take a look at the list above?  Checkboxes are applied to the bugs you discovered which were fixed.  I had one question about the "size" attribute issue which, I believe, isn't actually an issue.

Can you share your thoughts on that?

Really grateful for your feedback.  We were able to fix most of the things you identified.

**Comment by wmodes** [comment]
In what version are these bug fixes available?  And where?

**Comment by uzquiano** [comment]
These are in 1.5.8.  Closing for now.  This issue was tracking a lot of stuff at once so if something else comes along, please open a new ticket so we can track individually.
