### ISSUE TITLE
Radio field value not getting submitted.

### ISSUE THREAD

**Issue by vikramsawant786** [gitana/alpaca#209]
Consider below Alpaca Form, It has two Radio fields, one select field and one date field. After user is done selecting values and submits the form, values of date and select are received at the server but value for two radio buttons is not received. 

$("#field1").alpaca({
"schema":{"type":"object",
"properties":{
"0116":{"type":"string",
"enum":["Y",
"N"]},
"0117":{"type":"string",
"enum":["E",
"N"]},
"0103":{"type":"string",
"enum":["L",
"G",
"E",
"N"]},
"0104":{"type":"string",
"format":"date"}}},

"options":{"renderForm":"true",
"form":{"attributes":{"action":"http://localhost:9221",
"method":"post"},
"buttons":{"submit":{"value":"Update Record"}}},
"fields":{
"0116":{"type":"radio",
"label":"STATEMENT MESSAGE CRITERIA USAGE FLAG",
"name":"0116",
"removeDefaultNone":true},
"0117":{"type":"radio",
"label":"STATEMENT MESSAGE CRITERIA INDICATOR",
"name":"0117",
"removeDefaultNone":true},
"0103":{"type":"select",
"label":"DATE OPENED CRITERIA INDICATOR",
"name":"0103",
"removeDefaultNone":true},
"0104":{"type":"date",
"label":"DATE OPENED BEGIN DATE",
"name":"0104"}}}
});

**Comment by uzquiano** [comment]
What version of Alpaca are you using?  This seems to work just fine with the latest release.

**Comment by uzquiano** [comment]
Closing for now.  Please verify on the latest 1.5.8 and if still an issue, re-open with another example.  Just want to be able to reproduce.
