### ISSUE TITLE
jquery-hashchange git not found

### ISSUE THREAD

**Issue by deviant32** [gitana/alpaca#211]
I am getting fatal: repository 'https://raw.githubusercontent.com/gseguin/jquery-hashchange.git/' not found when trying to run a bower install.

**Comment by arthurportas** [comment]
Hi,

by some reason bower could not contact that uri. Try this one https://github.com/gseguin/jquery-hashchange.git

Cheers,

**Comment by uzquiano** [comment]
Awesome.  This is fixed in master.
