### ISSUE TITLE
message : Unable to find template descriptor for control: hidden

### ISSUE THREAD

**Issue by billbarsch** [gitana/alpaca#229]
When we try to render a form in "display" mode, if we have hidden fields on schema and options, this error occurs.
Please make alpaca ignore hidden fields on "display" views. Automatic remove them from my complex schemas and options is dificult and this solution seems to be simple. How can I do that?

**Comment by billbarsch** [comment]
I copy the "control-any" function and rename to "control-hidden"
And now it works perfectly!!

<pre>
this["HandlebarsPrecompiled"] = this["HandlebarsPrecompiled"] || {};
this["HandlebarsPrecompiled"]["web-display"] = this["HandlebarsPrecompiled"]["web-display"] || {};  
this["HandlebarsPrecompiled"]["web-display"]["control-hidden"] = function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "", stack1, helper, options, helperMissing=helpers.helperMissing;


  buffer += "<script type=\"text/x-handlebars-template\">\n\n    <div>";
//  stack1 = (helper = helpers.str || (depth0 && depth0.str),options={hash:{},data:data},helper ? helper.call(depth0, (depth0 && depth0.data), options) : helperMissing.call(depth0, "str", (depth0 && depth0.data), options));
//  if(stack1 || stack1 === 0) { buffer += stack1; }
  buffer += "</div>\n\n</script>";
  return buffer;
};
</pre>

**Comment by arthurportas** [comment]
Hi,

can you provide a live example on [codepen.io](http://codepen.io/) or [jsfiddle](https://jsfiddle.net/) to replicate your scenario?
It would also be great to see a pull-request on this!
Let us know if you need help.

**Comment by billbarsch** [comment]
To replicate just put some lines at the field "hidden" example page:
<pre>http://www.alpacajs.org/docs/fields/hidden.html</pre>

my changes on the default hidden example was:
add: 
```javacript
    "data": {
        "name":"asdfa",
     (...)
```
and add:
```javascript
(...)
    "view":{"parent":"bootstrap-display"},
(...)
```


just copy and paste this there:
(and the error shows up)
```javascript
$("#field1").alpaca({
    "schema": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "password": {
                "type": "string"
            },
            "token": {
                "type": "string"
            }
        }
    },
    "options": {
        "fields": {
            "name": {
                "type": "text",
                "label": "Username"
            },
            "password": {
                "type": "password",
                "label": "Password"
            },
            "token": {
                "type": "hidden"
            }
        },
        "form": {
            "buttons": {
                "submit": {
                    "value": "Log In"
                }
            }
        }
    },
    "data": {
        "name":"asdfa",
        "token": "12345"
    },
    "view":{"parent":"bootstrap-display"},
    "postRender": function(control) {
        var form = control.form;
        form.registerSubmitHandler(function() {
            alert("Token is: " + control.getValue().token);
        });
    }
});
```

**Comment by arthurportas** [comment]
@billbarsch

you're right. Following error printed:
```javascript
{"message":"Unable to find template descriptor for control: hidden"}
alpaca.min.js:4 Uncaught Error: Alpaca caught an error with the default error handler: {"message":"Unable to find template descriptor for control: hidden"}
```
Tried on [codepen](http://codepen.io/arthurportas/pen/ragRjb)
This needs work.

**Comment by jetsonjohn** [comment]
Any update on this issue. I have same requirement to hide a field in view mode bootstrap-display

**Comment by sleepycat** [comment]
:+1:

**Comment by uzquiano** [comment]
Added the control-hidden template to web-display so that hidden fields simply don't render in a display-only mode.  Committed to head and will be part of the next 1.5.10.

**Comment by billbarsch** [comment]
Hello Michael help me with this please it´s important:

https://github.com/gitana/alpaca/issues/277

2015-07-14 1:45 GMT-03:00 Michael Uzquiano <notifications@github.com>:
