### ISSUE TITLE
"collapsed" : true being ignored

### ISSUE THREAD

**Issue by xaviergonz** [gitana/alpaca#230]
v1.5.8.
In options, when collapsed is set to true it seems to be ignored (they always appear expanded).
Modes: all (create, display, edit)

Sample:

```
$("#field2").alpaca({
    "data": ["Mint Chocolate", "Choco"],
    "options": {
        "label": "Ice Cream",
         "collapsed":true
    },
    "schema": {
        "description": "My Favorite Ice Creams",
        "type": "array",
        "items": {
            "title": "Ice Cream",
            "type": "string",
        }
    }
});
```

**Comment by xaviergonz** [comment]
I think this one is related to the following line in src/js/views/bootstrap.js

 // set up container to be collapsible
$(containerEl).addClass("collapse in");

the "in" part of the class should not be there when collapsed is true for that field

**Comment by xaviergonz** [comment]
I think it is kind of "hacky" and most probably there's a better way to do it, but just FYI I made it work by making a container template for the bootstrap view that adds these attributes to the span element
```
 data-collapsed="{{#if options.collapsed}}true{{else}}false{{/if}}" class="alpaca-container-label-link"
 class="alpaca-container-label-span"
```
and added this to the postrender of such view
```
        "postRender" : function(control) {
          // find all controls with data-collapsed set to true and collapse their data-target

          function collapseElement($element) {
            var targetId = $element.data("target");
            $(targetId).removeClass("in");
          }

          var $fieldControl = $('*[data-alpaca-field-id="' + control.id + '"]');
          $('.alpaca-container-label-link[data-collapsed="true"]', $fieldControl).each(function() {
            collapseElement($(this));
          });
        }
```

**Comment by davidje13** [comment]
I've run into the same issue and fixed it by running this code before initialising the form, which I think is a bit less hacky:

    Alpaca.views["bootstrap-edit"].callbacks["collapsible"] = function() {
    	var $fieldEl = $(this.getFieldEl());
    	var $legendEl = $fieldEl.find("legend").first();
    	var $anchorEl = $("[data-toggle='collapse']", $legendEl);
    	if ($anchorEl.length > 0) {
    		var $containerEl = $(this.getContainerEl());
    		var id = $containerEl.attr("id");
    		if (!id) {
    			id = Alpaca.generateId();
    			$containerEl.attr("id", id);
    		}
    		$anchorEl.attr("aria-expanded", this.options.collapsed ? "false" : "true");
    		$containerEl.addClass(this.options.collapsed ? "collapse" : "collapse in");
    		if (!$anchorEl.attr("data-target")) {
    			$anchorEl.attr("data-target", "#" + id);
    		}
    		$anchorEl.mouseover(function(e) {
    			$(this).css("cursor", "pointer");
    		})
    	}
    };

(this basically just patches the `callbacks["collapsible"]` method in https://github.com/gitana/alpaca/blob/master/src/js/views/bootstrap.js and could easily be merged in)

**Comment by scottseeker** [comment]
Any reason not to put this into a pull request?  If no one is interested in doing it I will see if there is a good way to put in davidje13's fix as that is what I'm using with success.

**Comment by uzquiano** [comment]
This has been fixed in head.
