### ISSUE TITLE
"collapsible": true being ignored in display mode

### ISSUE THREAD

**Issue by xaviergonz** [gitana/alpaca#231]
v1.5.8.
In options, when collapsible is set to true (or not set) it seems to be ignored (the array can never be collapsed).
Modes: display

Sample:
```
$("#field2").alpaca({
    "data": ["Mint Chocolate", "Choco"],
    "options": {
        "label": "Ice Cream",
        "collapsible":true
    },
    "schema": {
        "description": "My Favorite Ice Creams",
        "type": "array",
        "items": {
            "title": "Ice Cream",
            "type": "string",
        }
    },
    "view" : "bootstrap-display"
});
```

**Comment by xaviergonz** [comment]
To fix this I think in src/templates/bootstrap-display/container.html, this part:
{{#if options.label}}
        <legend class="{{#if options.labelClass}}{{options.labelClass}}{{/if}} alpaca-container-label">{{{options.label}}}</legend>
        {{/if}}

needs to be changed to this:
{{#if options.label}}
        <legend class="{{#if options.labelClass}}{{options.labelClass}} {{/if}}alpaca-container-label">

            {{#if options.collapsible}}
            <span data-toggle="collapse">
            {{/if}}

            {{{options.label}}}

            {{#if options.collapsible}}
            </span>
            {{/if}}

        </legend>
        {{/if}}

**Comment by xaviergonz** [comment]
I can confirm that doing that change fixes the issue

**Comment by SuperSeb92** [comment]
Why don't you submit a PR with you fix?

**Comment by xaviergonz** [comment]
Done!

**Comment by xaviergonz** [comment]
Since it has been now merged I will close the issue.
