### ISSUE TITLE
valid required enum in display mode shown as invalid

### ISSUE THREAD

**Issue by xaviergonz** [gitana/alpaca#233]
v1.5.8
When there is a valid enum marked as required it shows a validation error in display mode
Modes: display

Sample:
```
$("#field2").alpaca({
    "data": "two",
    "schema": {
        "type": "string",
        "required":true,
        "enum": [ "one", "two", "three" ]
    },
    "view":"bootstrap-display"
});
```
Running it gets you:

two
 This field is not optional.
 This field should have one of the values in one, two, three. Current value is: two

**Comment by hardikkaji** [comment]
@xaviergonz  

Just take a pull of latest version of alpaca. 

It's working fine in it.

**Comment by uzquiano** [comment]
Yep, verified.  Thanks @hardikkaji for the test.  Closing this one.
