### ISSUE TITLE
Define an Id for buttons (e.g. submit) via options

### ISSUE THREAD

**Issue by maweber** [gitana/alpaca#236]
It seems that it is no longer possible to assign an id for buttons, using schema options.
In version 1.1.3 something like this worked

```javascript
(...)
"form": {
        "buttons": {
            "reset": {},
            "submit": {
                "id": "my_id"
            }
        },
        (...)
    }
```

**Comment by arthurportas** [comment]
Hi @maweber,

you're right, this is not working with recent builds. If you really need this feature, should be fairly simple to implement it.
Modify templates in : src\templates\xxx\form.html to write id attribute and src\js\Form.js to store id value inside options object.
Let me know if it works.
Cheers,

**Comment by maweber** [comment]
Thanks for your reply,

I'm away for 1-3 weeks, but I will consider this option once I'm back
and let you know it worked.

best

Am 02.04.2015 um 15:56 schrieb Arthur Portas:

**Comment by arthurportas** [comment]
Hi @maweber @uzquiano 

i've submitted a pull-request on this issue [PR-243](https://github.com/gitana/alpaca/pull/243) .
Cheers,

**Comment by uzquiano** [comment]
This PR was merged and is in head.  Will be part of the next 1.5.10 release.
