### ISSUE TITLE
Can't import alpacajs by jspm/systemjs 

### ISSUE THREAD

**Issue by zmmail** [gitana/alpaca#241]
Please refer to https://github.com/jspm/jspm-cli/issues/641.
Mr guybedford feedback alpaca is using a named define - so it's not AMD-compatible. 
I think if alpacajs remove the named define? It's will ok. Thanks!

**Comment by uzquiano** [comment]
Looked over that ticket and it sounds like, for now, you guys are squared away with a shim.  If you have any suggestions for improvements to our UMD wrapper, submit a PR or let us know what to change.

We're hip but perhaps not as super fly at AMD as you guys. Let us know what we can do.  I'll close this for now but feel free to submit another ticket (or re-open this) with anything you feel we can do?
