### ISSUE TITLE
How does alpaca preserve field order?

### ISSUE THREAD

**Issue by musicist288** [gitana/alpaca#249]
This may be a trivial question, but looking at the schema definition structure, I realized that the data structure uses almost solely objects, so how does alpaca guarantee that the fields will be displayed in the order they are defined, if it does at all ?  I know browsers tend to preserve the key order when iterating through objects, but that's not guaranteed by the language spec.

**Comment by uzquiano** [comment]
If you use a layout template, you can drop down fields in any order and anywhere on the page as you wish.  On the other hand, if you just run Alpaca and let it do it's vertical stacking, then the order is the order provided by the browser's JSON library.  Which, as you point out, isn't guaranteed to provide consistent ordering.

One interesting option would be to provide an "order" field option that could tell the wrapping container the presentation order of elements.

**Comment by musicist288** [comment]
Thanks for the info. I took a stab at a pretty basic implementation of adding an `order`property on the ObjectField as I'm expecting to generate forms specified by a completely different team, so I don't want to have to adjust layout files. I'd appreciate if you would look it over/let me know if there are any issues with it.

**Comment by beccon4** [comment]
An easier and more consistent solution would be to allow arrays as a structure element as they preserve the order of their elements.
