### ISSUE TITLE
How to work with form outside of main alpaca function?

### ISSUE THREAD

**Issue by adamrenner** [gitana/alpaca#261]
Following the many tutorials, I can see that the main intent is to use alpaca strictly through the alpaca function. I want to be able to manipulate the form after creating it and check for or receive a callback indicating the all of the required fields are filled in. I need a seperate indicator on the page that indicates when required fields are completed, regardless of the schema used to create the form.

After creating a form like the one below, How can I access my form object and is there a way to check that required fields are completed or to set a callback when they are?

                $("#form").alpaca({
                    "schema": "./myschema.json"
                });

**Comment by uzquiano** [comment]
Use the postRender callback to grab an instance of the top level rendered control once the render is complete. Then go to town with it.
