### ISSUE TITLE
How do I refresh?

### ISSUE THREAD

**Issue by jimijon** [gitana/alpaca#263]
Hello -

I need to refresh my schema overtime a user answers questions on my form.
I know how to do field.scheme.enum = something, but how do I refresh an 
individual field? 

As a question is answered my rules dictate what the schema should be.

What is the command to reload the schema?
thanks

**Comment by uzquiano** [comment]
There is a refresh function on every field.  You can do things like:

field.on("change", function() {
   otherField.schema.required = true;
   otherField.refresh(function() {
      console.log("Refresh completed");
   });
});

The newly rendered field will replace the old one and will have the new schema applied to it.  It destroys the old DOM element.  If you want to copy state to the new control instance, you'll need to set .data onto it ahead of the refresh.

**Comment by uzquiano** [comment]
I'll close this but feel free to re-open if this doesn't cover the issue.
