### ISSUE TITLE
ObjectField#addItem does not mark up the new field correctly

### ISSUE THREAD

**Issue by robustified** [gitana/alpaca#264]
When you use addItem to add a field to an onject (like at the top level of the form), it adds the field, but fails to add the container item wrapper (div.alpaca-container-item with a few additional attributes) that is found on initial rendering for the new item. I found that the new field object contains the wrapper element as containerItemEl, with all the attributes properly set (like the rest of the fields in the object), but containerItemEl is it inserts newField.field into the dom and not containerItemEl. I managed to get around this by doing this:

newField.field.replaceWith(newField.containerItemEl);
newField.containerItemEl.append(newField.field)

effectively switching the inserted dom element to the item container and putting the inserted element into that container. Whether or not this maintains the state correctly internally is not 100% clear yet but it seems to on initial inspection.

**Comment by uzquiano** [comment]
Thanks for the feedback.  Is this on the latest version of Alpaca?  Just want to make sure so that we can verify.

**Comment by robustified** [comment]
We are on 1.5.8, but I see 1.5.9 is available on bower now. I'll try that to make sure the behavior is the same.

**Comment by robustified** [comment]
Is there any plan to make this available via npm? Just curious.

**Comment by robustified** [comment]
I can confirm that this is an issue on 1.5.9 as well.

**Comment by uzquiano** [comment]
Thanks for checking.  No plans for npm yet.  Not a bad idea though.  If you could submit an issue for that, then we can let community upvote it.  I don't see why not, just need to adjust the deployment scripts to push there.

**Comment by robustified** [comment]
Will do, thanks!

**Comment by uzquiano** [comment]
This has been fixed in head.  Thanks!
