### ISSUE TITLE
ObjectField#wizard does not manage container items correctly

### ISSUE THREAD

**Issue by robustified** [gitana/alpaca#267]
The function ObjectField#wizard manages the set up and re-arrangement of all the child fields it's responsible for, however it does not seem to do the same with the **div.alpaca-container-item** (referenced by child objects as **containerItemEl**) elements or the **div.alpaca-container** (referenced by the ObjectField itself as **container**). It simply leaves those elements (now empty) at the top of the **field** element of the ObjectField. Those containerItemEl elements have a margin, leaving some extra whitespace in the form, and the layout of the fields seem to depend on that margin to look correct. Moving the elements to what I think was the "correct" place (wrapping the individual field's field elements like they were) manages to fix the display issues, but I'm still not sure if by doing that I'm screwing up the state of the ObjectField itself, or of the wizard. It still seems to switch correctly, so I think that appears to be fine, unless there are other side-effects. I also moved the **container** element to wrap the **div.alpaca-wizard** element that gets created. Not sure if this is "correct" either.

**Comment by uzquiano** [comment]
This is fixed in head.  It appears to only happen for the autowizard mode (using bindings to DOM columns).  Actual template-driven layouts seem to work fine.

Also set it so that the original container, if child size === 0, sets itself to display:none.  I think this should solve your margin problem.  

Thanks for the detailed issue!

**Comment by robustified** [comment]
Thank you very much!
