### ISSUE TITLE
Custom rendering function for grid columns 

### ISSUE THREAD

**Issue by yogeshmsharma** [gitana/alpaca#269]
There has to be way to add custom rendering function, which will be applied to single column for displaying user defined render function

**Comment by yogeshmsharma** [comment]
any update on this?

**Comment by hardikkaji** [comment]
Can you more elaborate please?

**Comment by yogeshmsharma** [comment]
ex: In data grid you have 3 columns viz Currency, zip and URL.
Currency should be prefix with $, zip should have format 9999 and URL as href

**Comment by uzquiano** [comment]
Sounds pretty cool.  If anyone has a pull request with an implementation or some ideas, feel free to submit them. The TableField is an example of a grid-like (obviously table) rendering where you can fully control all of the rows and columns using JSON schema.  It would be neat to provide something like this for the GridField as well.

**Comment by uzquiano** [comment]
In general, "custom rendering functions" means "custom field" in Alpaca.  You can create your own fields and define exactly how they render and then use them as you wish.  Including in columns within tables.  I'll close this.  If this doesn't solve the issue, please provide a more specific use case and sample code via a Fiddle.
