### ISSUE TITLE
Lazy data loading in select field

### ISSUE THREAD

**Issue by yogeshmsharma** [gitana/alpaca#275]
In a single form if we have 10 data combo and all are loading data from server. Page loading becomes very slow. We should have option of loading data in lazy manner using ajax.

we should implement lazy loading as well as lazy rendering for faster response time

**Comment by hardikkaji** [comment]
Solution 1: You can send one ajax call to server which gives you all combo data. And then you can use dataSource property of select by assigning him callback function.

```
{
 drp1:{[
  {text:"text", value:"val"},
  {text:"text", value:"val"}
  ]},
  drp2:{[
   {text:"text", value:"val"},
   {text:"text", value:"val"}
   ]}
}
```
response from server will be on above format.
```
var data;
$.ajax({url:"getData.html", sucess:function(res){
data = res;
}});

$("#field10").alpaca({
    "options": {
        "dataSource": function(callback) {
            callback(data.drp1);
        },
        "label": "Select your favorite flavor of ice cream",
        "type": "select",
        "multiple": true,
        "size": 3
    }
});
```

Solution 2: You can direct send ajax call to server in dataSource callback for each combo.

Regards,

**Comment by hardikkaji** [comment]
@uzquiano We should close this issue.!

**Comment by uzquiano** [comment]
Thanks guys.  Glad it worked out.  The data source loading has been enhanced a good bit in head.  However, the syntax and mechanisms you describe are perfectly correct.

**Comment by hardikkaji** [comment]
@uzquiano Cool.. :+1:
