### ISSUE TITLE
PROBLEM with Arrays!!

### ISSUE THREAD

**Issue by billbarsch** [gitana/alpaca#277]
Big problem with arrays here!!
Very easy to reproduce on arrays example page:
http://www.alpacajs.org/docs/fields/array.html

If we add a new "item" by click on toolbar add button, the indexes (attribute "name") are recalculated and update correctly! (ok)
If we add a new "item" by click on LAST add button (on the LAST item), the indexes (attribute "name") are recalculated and update correctly! (ok)

BUT:
If we add a new "item" by click on add buttons on the middle of other items, the indexes ARE NOT RECALCULATED! 
The attribute: "name" remains the same below the NEW LINE and the duplicity of "names" causes data loss!!!

**Comment by arthurportas** [comment]
Hi @billbarsch @uzquiano 
Can you place a breakpoint  on 'postRender: function(callback)' in alpaca.js. Then go upwards to debug. Filed wrapper div element data attributes(data-alpaca-field-path, data-alpaca-field-name, name) and field attribute (name) are not being set accordingly. Needs fix.
![image](https://cloud.githubusercontent.com/assets/6153945/8851189/c0357758-3145-11e5-8a39-1e5f692e8511.png)
Let us know your progress.
Cheers,

**Comment by billbarsch** [comment]
my print with the same error:

![error](https://cloud.githubusercontent.com/assets/4331821/8877626/a3c90686-31fc-11e5-9a43-d70c89b86696.jpg)

**Comment by billbarsch** [comment]
My systems using alpaca are on production, so...
Until a real fix is created, I´m using this temporary solution removing the add button (with the error) via css: (it shows only the last "add" button, and the names recalculations seems to be ok)


    .alpaca-array-actionbar-action[data-alpaca-array-actionbar-action="add"]{
        display:none;
    }  

    .alpaca-container-item-last > div > div > .alpaca-array-actionbar-action[data-alpaca-array-actionbar-action="add"]{
        display:block!important;
    }  
'''

**Comment by uzquiano** [comment]
Thanks for sharing this.  Definitely an issue.  Took a look and found a few improvements around how we handle DOM element refreshes on nested items.  Cleaned this up in head.  Could you take a look with a build from the tip on master?

**Comment by billbarsch** [comment]
thanks very much!! I will go there rigth now

Em sábado, 25 de julho de 2015, Michael Uzquiano <notifications@github.com>
escreveu:

**Comment by uzquiano** [comment]
Hi Bill, did this fix the issue for you? Let me know if you have any feedback on the dom elements.

**Comment by billbarsch** [comment]
Hello @uzquiano 
I´m trying to compile alpaca on my ubuntu but I´m getting some errors, I think it´s not a alpaca problem, I used to download alpaca directly from the cdn, so I can't test the new changes right now. I´ll have to wait you release the alpaca.js file.

![error compile](https://cloud.githubusercontent.com/assets/4331821/8892594/7ddbe2ae-3337-11e5-8120-e377a932412a.png)

**Comment by arthurportas** [comment]
Hi @billbarsch 
i've sent you an email with latest commit build.
Give us feedback.

**Comment by billbarsch** [comment]
Thanks @arthurportas, but I´v got some errors and I tried to look the other way:
I open the commit page created by @uzquiano 
https://github.com/gitana/alpaca/commit/efea4216abe53c48a887418ec1b89fe103cfd89c
And update my alpaca-1.5.11.js file by myself
So I apply the changes line by line and now IT´S WORKING!

But @uzquiano please take a look at this lines:
https://github.com/gitana/alpaca/pull/278
When I start updating my alpaca-1.5.11.js, I have noticed the function "updateChildDOMElements" doesn´t exists anymore. Please check if my pull request make sense.

**Comment by billbarsch** [comment]
One little error here:
```javascript
   handleRepositionDOMRefresh: function()
        {
            var self = this;

            if (self.getParent())
            {
                // call update dom markers for parent which will trickle down to to cover this field and our siblings
                self.parent().updateDOMElement();
            }
            else
            {
                // just ourselves
                self.updateDOMElement();
            }
        },
```

this line:
```javascript
                self.parent().updateDOMElement();
```
seems to be:
```javascript
                self.parent.updateDOMElement();
```

I´m getting this error:
"parent()" not a function

**Comment by uzquiano** [comment]
Nice catch.  Yes, that was a bug.  Changed to use getParent().  
This has been fixed in head.

I'll close this assuming that we're all good on this issue now.  If something else comes up, can you either re-open or create a new issue?  Thanks!

**Comment by billbarsch** [comment]
Hello!
I think the same error occurred on 1.5.14 version. Let´s take the example page:
http://alpacajs.org/docs/fields/array.html
Is easy to get inputs with the same name: just click to delete the first item, than add a new item on top:
![1](https://cloud.githubusercontent.com/assets/4331821/10657457/1ffc163e-7862-11e5-8e6a-019abb6136be.PNG)
