### ISSUE TITLE
Template Rendering in New Alpaca Version

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#283]
Dear Team,

I am using below Template code in Alpaca old version and it's generating proper template.

```
{{#if options.label}}<h3>${options.label}</h3>{{/if}} 
  {{#if options.helper}}<h4>${options.helper}</h4>{{/if}} 
     <div class="row"> 
         <div id="d1_1" class="col-md-4"> </div>  <div id="d1_2" class="col-md-4"> </div>  <div id="d1_3" class="col-md-4"> </div>  
     </div> 
      <div class="row"> 
         <div id="d2_1" class="col-md-4"> </div>  <div id="d2_2" class="col-md-4"> </div>  <div id="d2_3" class="col-md-4"> </div>
     </div> 
```

Now in Alpaca The 2nd Class='row' is not rendering in HTML Page while using template.

Please look into it.

**Note:** I'm in process of migration to new version of alpaca i.e. 1.5.11 from 1.1.3.

Regards,

**Comment by uzquiano** [comment]
Not sure but I do know that the older versions of Alpaca were using the now retired jQuery tmpl() engine.  The 1.5.x branch uses Handlebars and so the syntax is a little different.

**Comment by hardikkaji** [comment]
Can you share the syntax?

For above template how i can generate above template in newer version?

In newer version only for div with class is considered while rendering HTML
and other div class rows are neglected.

**Comment by uzquiano** [comment]
The syntax is just standard Handlebars syntax:

http://handlebarsjs.com/

**Comment by hardikkaji** [comment]
Agreed.

But why only first div class row is considered while generations of
templates?

Need some light on that.

Because above same code works in older version

**Comment by hardikkaji** [comment]
Dear @uzquiano ,

Waiting for your replay.!

Regards,

**Comment by uzquiano** [comment]
I don't really have much to add here.  Perhaps the community can help.  The only thing I can recommend is to look at how the existing templates are implemented and work backwards.

I'll close this ticket as it's deviating away from an actual bug/issue.  Feel free to open a new ticket if there's something that you can verify to be broken and can be fixed, etc.
