### ISSUE TITLE
Refreshing particular Control

### ISSUE THREAD

**Issue by hardikkaji** [gitana/alpaca#285]
Dear Team,

I have requirement to refresh particular control after changing some of it's fields property & schema property how can I able to do it?

**Note:** I'm using as of now Alpaca 1.1.3 version.!

Regards,

**Comment by uzquiano** [comment]
On 1.5.x, you can call:

````
field.refresh();
````

With respect to any earlier versions, my recommendation is to upgrade to the latest 1.5.x since we don't actively concern ourselves with the older codebase.
