### ISSUE TITLE
Table field incompatible with DataTables 1.9

### ISSUE THREAD

**Issue by davidcwalker** [gitana/alpaca#287]
Using the table field type with an older version of DataTables (prior to 1.10) results in the following Javascript error:

TypeError: jQuery.fn.dataTableExt is undefined

It's not clear from the documentation or the examples whether this is simply an issue with that version of DataTables or if bootstrap.js and jquery 1.10+ are also required.  None of these dependencies are addressed in the documentation or examples.

**Comment by uzquiano** [comment]
This is likely true.  Check bower.json for third party dependency versions.  In this case, for data tables, at the time of this writing is 1.10.5  That's what we've tested against.  Very possible that it would break on earlier versions, so be sure to test on your own.
