### ISSUE TITLE
Order option in wizard

### ISSUE THREAD

**Issue by altais** [gitana/alpaca#288]
Hi, 
I'm trying to order fields (like this issue https://github.com/musicist288/alpaca/commit/e58a03712566c1e44b402b705f044d9dbdf7475d), it works perfectly with the basic style but when i try with Wizard order is ignored.
Do you know how to solve this bug?
Thx

**Comment by tnguyen42** [comment]
Hi!

Glad I'm not the only one on this one. I've been facing the same problem for almost a week.
Anyone knows how to reorder the form in Wizard mode?

Thanks in advance.

**Comment by uzquiano** [comment]
Just pushed a commit up to master so that the wizard respects the "order" field during auto-mode field binding.  It will be in the next release.  In the meantime, please give it a shot if you can build from head.

**Comment by altais** [comment]
It's working perfectly :) Thanks !
