### ISSUE TITLE
Nested Array Actionbar Actions point to the wrong container

### ISSUE THREAD

**Issue by jamesmcb** [gitana/alpaca#291]
When setting the actionbar in a nested array, the action buttons interact with the first element rather than it's respective element.  

To reproduce this:

1. Go to this JSFiddle:  https://jsfiddle.net/44gopwdc/2/
2. Remove the last element "d"
3. Witness "b" disappear

This works when you don't specify the action bar:

1. Go to this JSFiddle: https://jsfiddle.net/pgsr3kr2/1/ ( the only thing different is the removal of the actionbar reference )
2. Remove the last element "d"
3. Witness "d" disappear

I'm pretty sure this is a bug and not an example of bad configuration.

**Comment by uzquiano** [comment]
This is fixed in head.
