### ISSUE TITLE
JSON Schema type: ['integer','null'] not supported

### ISSUE THREAD

**Issue by nikmartin** [gitana/alpaca#292]
I have  a JSON schema for a field:
```
  'age': { // age
      title: 'Your age',
      type: ['integer','null'],
      minimum: 1,
      maximum: 120
    }
```
And alpaca throws the error:
`Uncaught Error: Alpaca caught an error with the default error handler: {"message":"Unable to find field class for type: undefined","reason":"FIELD_INSTANTIATION_ERROR"}`

Is it possible to support multiple types for a field in Alpaca? I need to be able to support null in an integer field that is required. It's a required field, but null or an integer are valid values.

**Comment by uzquiano** [comment]
This isn't supported right now.  Would an alternative approach be to support a flag that says "allow null"?

**Comment by nikmartin** [comment]
Possibly, but I'd have to see what the implementation would look like in regards to my schema validation on the schema side

**Comment by uzquiano** [comment]
Okay.  There isn't any plan to support multiple data types per field instance.  The alternative mentioned above is a possibility.  If you think that's the way to go, please open another ticket with that request.  Closing this.
