### ISSUE TITLE
Jquery: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jamesmcb** [gitana/alpaca#300]
I am using alpaca.js as a form builder where individuals can create many fields (as many 100-300 on one screen).  However, it seems like alpaca.js is unable to handle that many and is exceeding memory capacity of browsers.  Any recommendations?

**Comment by arthurportas** [comment]
HiAny example to reproduce?What browsers envolved?32 or 64 bit versions?Could be related to GC, heap memory leaks and so on...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: jamesmcbSent: Segunda-feira, 31 de Agosto de 2015 18:56To: gitana/alpacaReply To: gitana/alpacaSubject: [alpaca] Jquery: Uncaught RangeError: Maximum call stack size exceeded (#300)I am using alpaca.js as a form builder where individuals can create many fields (as many 100-300 on one screen).  However, it seems like alpaca.js is unable to handle that many and is exceeding memory capacity of browsers.  Any recommendations?

—Reply to this email directly or view it on GitHub.

**Comment by jamesmcb** [comment]
I'm currently using Chrome Version 44.0.2403.157 (64-bit) on Mac OS 10.10.3


1. Go to http://jsfiddle.net/arqcs9nu/
2. Open up jquery console
3. Click Run
4. Wait 2-5 minutes for it to render
5. Console will show "Uncaught RangeError: Maximum call stack size exceeded"
![screen shot 2015-09-01 at 11 21 43 am](https://cloud.githubusercontent.com/assets/778372/9612651/ba3537d8-509b-11e5-86b3-9bf9dbed23c0.png)

**Comment by jamesmcb** [comment]
Here's a version with the wizard and custom fields removed: http://jsfiddle.net/arqcs9nu/1/  Same issue.

**Comment by nmangwanda** [comment]
I had the same issue and it was related with a JSON data property being returned as empty "", changing these to null explicitly fixed the issue.

**Comment by uzquiano** [comment]
This was fixed in head.  Added some additional nextTicks on the validator compiler which works better for the very long arrays that you had in your sample.

**Comment by quantegy** [comment]
I had this problem with the Google Map API in creating a marker instance. If Google is not going to open source their Javascript Map API, then they need to step up their error handling game.

**Comment by DannyGokey** [comment]
@quantegy 
you saved my day!! thanks.
