### ISSUE TITLE
problem in designer part

### ISSUE THREAD

**Issue by meisam3322** [gitana/alpaca#302]
hi,

in designer section, form builder, when user remove all added items, can't add again any item.

**Comment by uzquiano** [comment]
The free designer that we include on the site likely has some weaker points and interesting places where improvements could be made.  It is intended as an example of what could be done.  It isn't part of the core Alpaca forms engine.

If you fix something, feel free to submit a pull request.  We'll get it merged in.

Also, I know a number of folks out there have innovated with Alpaca form designers of their own.  If anyone wants to promote something they've built in the form designer's stead, we'd be happy to link it to the web site.
