### ISSUE TITLE
Default collapsible false

### ISSUE THREAD

**Issue by basvandenheuvel** [gitana/alpaca#311]
In my opinion the option to not allow the user to collapse your form should be enabled by default.
Currently i have to set `"collapsible": false` for all my objects, this seems the wrong way around. I doubt there are websites who implement alpaca with the possibility to collapse the form.

What's your opinion?

**Comment by uzquiano** [comment]
Anyone have thoughts on this?  I'm fine with changing the default to collapsible: false if that's what folks want.

**Comment by uzquiano** [comment]
I set collapsible to false by default in head.  We'll see if anyone spots this and complains.  If not, then you were right and we can assume false by default going forward.
