### ISSUE TITLE
TinyMCE fails to initialize when nested inside a ContainerField.

### ISSUE THREAD

**Issue by Neopallium** [gitana/alpaca#312]
TinyMCE fields fail to initialize when used inside a container field.

```
$("#field1").alpaca({
    "schema": {
    	"type": "object",
    	"properties": {
    		"field1": {
    		}
    	}
    },
    "options": {
    	"type": "object",
	    "fields": {
		    "field1": {
			    "type": "tinymce"
    		}
	    }
    }
});
```

**Comment by uzquiano** [comment]
This works in head.  I suspect it was fixed when we introduced the "ready" event that fires post-DOM render.  The CKEditor and TinyMCE editors listen for that now.  Probably affected this.
