### ISSUE TITLE
Alpaca.registerView not allowing caching of ajax requests

### ISSUE THREAD

**Issue by deviant32** [gitana/alpaca#317]
I have several views that I am registering.  I need to utilize client side caching but in the server response I am getting: 

Cache-Control:max-age=0, no-cache

Even though i have my nginx server config set to cache for 1 month.  Is it the ajax request that is disabling the caching?

**Comment by NickAtSchool** [comment]
This may be a result of submitting POST requests. I'm guessing this issue is old now, though. That said, if someone reading this is desperate for a solution, you could always hack in something to load/store the server response in localstorage before handing it off to alpaca.

**Comment by uzquiano** [comment]
Would like to hear more about this.  If anyone has a reproduction case using fiddle or something like that, would love to take a look.  Will close for now.
