### ISSUE TITLE
Moment.js no longer global

### ISSUE THREAD

**Issue by ed0wolf** [gitana/alpaca#328]
DateTimeField requires Moment.js, it assumes moment is available globally but moment has recently stopped setting itself on the window and so Alpac abreaks when trying to access it.

I have fixed a work around this in my project by injecting it in the AMD define call.

**Comment by uzquiano** [comment]
Alpaca now has a helper method to assist it with finding the moment object.  Right now, it simply looks to window.moment for this object.  In the future, we might introduce other behavior.

With respect to AMD, one recommendation for now is to export the "moment" variable via a shim.  We do this within our own applications using require.js.  If you can't do that, then your solution works as well - to require moment in and then set it to the global "window" context.  You can also set it to Alpaca._moment which is where Alpaca stores it's cached reference.

**Comment by uzquiano** [comment]
In addition, on master branch, upgraded moment.js to latest version.
