### ISSUE TITLE
Enum reordered alphabetically, not in order specified in schema

### ISSUE THREAD

**Issue by samrispaud** [gitana/alpaca#329]
Why is the enum array re-ordered to be alphabetical for radios/inputs/etc? Shouldn't the options display in the order they are specified in the schema. See attached.
![screen shot 2015-11-10 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/10902468/11075269/5d5f8fd2-87c2-11e5-8ea7-aaac3135e0e9.png)

**Comment by cebas** [comment]
+1

**Comment by uzquiano** [comment]
The default is to sort alphabetically.  A lot of people wanted that and so we've made that the default.  You can adjust this using the "sort" option.

See:
http://www.alpacajs.org/docs/fields/select.html example #2

You can do:
options.sort = false
This will remove any sorting behavior and preserve your order.

Or you can do:
options.sort = function(a, b) { return 0; }
This lets you provide a custom sort method.  Returning 0 means you have no preference between two items (a and b) in the list.

**Comment by quakedc** [comment]
options.sort = false doesn't seem to work for me (in 1.5.14).

options.sort = function(a, b) { return 0; } works

Not a bug but just wanted to see if others are experiencing the same thing.

**Comment by cniesen** [comment]
Yeah, `"sort" : false` isn't a supported options.  Using the function theoretically works but it's not a valid JSON syntax so processing the JSON with anything else than JavaScript will fail.

**Comment by cniesen** [comment]
Pull request #339 adds the `options.sort = false` support that @uzquiano mentioned.
