### ISSUE TITLE
Observables example #1 seems incorrect

### ISSUE THREAD

**Issue by quakedc** [gitana/alpaca#331]
The first example at: http://www.alpacajs.org/docs/api/observables.html doesn't seem to be correct.

When Milwaukee is selected (as default), the correct teams are displayed. However, when I select Cleveland, I get Brewers Browns and Bucks (instead of Indians Cavaliers and Browns) and when I then select Boston, I get Brewers Browns Bruins and Bucks (instead of Red Sox Celtics Patriots and Bruins).

Instead of strictly using the new enum, it seems like it is being appended to the old one and some weird selection is going on. This should be a bug right? If so, can someone please fix this? I've been doing something similar in my app with selects and it's also broken.

The second example seems fine but I don't want to use datasource/callback.

This is a separate question but does anyone know if there is an option to output the enum as is and not in sorted order?

(I've also posted this as a comment on that page but figured I also post here as well.)

**Comment by uzquiano** [comment]
I believe this is fixed in head.  If so, it'll be part of the next release.  If not, we'll sort this out.

**Comment by quakedc** [comment]
Great! I'll look for it in the next release. Thanks for the quick response.
