### ISSUE TITLE
adding a new option label item in Select Field, on Form Builder, it get an error

### ISSUE THREAD

**Issue by simonemedasfedro** [gitana/alpaca#335]
Error is:
Alpaca encountered an error while previewing form -> Unable to find field class for type: string
reason: "FIELD_INSTANTIATION_ERROR"

replacing:
                    "optionLabels": {
                        "type": "array",
                        "items": {
                            // "type": "string" // ORIGINAL
                            "type": "text" // my edits
                        }
                    },
in the getOptionsForOptions method, the issue seems fixed (file: bootstrap/alpaca.js).

**Comment by 78Gills** [comment]
i have encountered a similar issue and i am glad to report that the suggested fix worked. 

the erring function starts in line: 11548

/**
         * Returns Alpaca options for the Alpaca options that are managed by this class.
         *
         * @private
         * @returns {Object} Alpaca options for the Alpaca options that are managed by this class.
         */
        getOptionsForOptions: function() {}

(file: bootstrap/alpaca.js).

**Comment by uzquiano** [comment]
Great find.  Fixed in head.
