### ISSUE TITLE
Error when I'm initializing dates

### ISSUE THREAD

**Issue by cagc4** [gitana/alpaca#343]
Hello Guys, 

I've the next error.
> Uncaught TypeError: Cannot read property 'date' of undefined **alpaca.min.js:10 **

I've tried with the  alpaca old version and the error doesn't happen

Thanks for your help

My Code:

<div id="field1"></div>
        <script type="text/javascript">
            $("#field1").alpaca({
            "data":{ 
                "Campo1":"15/10/01"
            },    
            "schema": {
                "type": "object",
                "properties": {
                    "Campo1": {
                     ** "format": "date"**,
                      "type": "string",
                      "required":true
                    }
                  }
            },
            "options": {
                "renderForm": true,
                "fields": {
                    "Campo1": {
                      "label": "Fecha",
                      "dateFormat": "DD/MM/YY"
                    }
                }
            },
            "view": {
                "parent": "bootstrap-edit-horizontal"
            }
    });
</script>

**Comment by uzquiano** [comment]
This works when I try it from the alpacajs.org web site.  You can plug this in to any of the examples and run it and it works.  I suspect you're missing a dependency.  Please check your JS includes and compare with the HTML of the alpacajs.org site to see what's missing.
