### ISSUE TITLE
Optional/"Or" dependencies

### ISSUE THREAD

**Issue by mikeyudin** [gitana/alpaca#348]
Hello,

Is it possible to have a property dependent on one field **or** another? For instance, I want to show a field if a user chooses "Yes" to Field A **or** "Yes" to Field B.

Looking through the source, it looks like I can only do Field A = "Yes" **and** Field B = "Yes".  Am I missing a possible feature?

Thanks.

**Comment by uzquiano** [comment]
No.  I don't think this is possible at the moment.
