### ISSUE TITLE
how can i change the language and column order from the upload field preview table?

### ISSUE THREAD

**Issue by devmerz** [gitana/alpaca#349]
I can't change the column order from the upload file preview table, either the language from the table header (Thumbnail, Name, Size, Actions)

[http://www.alpacajs.org/docs/fields/upload.html](url)

![upload file error](https://cloud.githubusercontent.com/assets/5478401/12989355/98b5380e-d0db-11e5-8f7f-ae2a7bbc5722.png)

**Comment by uzquiano** [comment]
All of this is done within the templates that drive the control.  The thing to do is to extend the UploadField with your own JS class and then adjust the HTML for the template as you see fit.  The ones that are provided should serve as a good entry point for figuring things out.
