### ISSUE TITLE
No template for file upload control in web implementation.

### ISSUE THREAD

**Issue by scottseeker** [gitana/alpaca#376]
There is no default control-upload, control-upload-partial-download, or control-upload-partial-upload templates for the 'web' version of alpaca.  This means you can't use a file upload control unless you use the Bootstrap version of Alpaca which has the templates implemented.

There are templates available available in the Bootstrap version that can be used as a reference.

**Comment by keitarobr** [comment]
Hi, is there any documentation on how to implement it? Specially regarding how to work with handlebars.

**Comment by scottseeker** [comment]
There is the documentation from handlebars site but other than that you may need to dig through code or look at other templates to see what is available to the template.  I believe options, schema, and data are all available.
