### ISSUE TITLE
Logic support for the form elements?

### ISSUE THREAD

**Issue by chunchill** [gitana/alpaca#402]
Really a great work!
But I have another idea about this project, does it support form logic?
for example, the visibility of the form is depend on the value of some other elements in the form.
like www.jqueryformbuider.com

**Comment by jongarrison** [comment]
http://www.alpacajs.org/docs/api/dependencies.html

**Comment by jongarrison** [comment]
The jQuery Form Builder looks interesting, but it appears to miss one of the main important features of Alpaca Forms which is that the forms are defined in JSON Schema.  This allows for many persistence and validation options that are extra work to implement if you are just working with html forms.

**Comment by sachatrauwaen** [comment]
I create a simple alpaca form builder prototype.
The form builder is made with alpaca and generate a realtime preview.
It generate also the schema and oprions for alpaca.

Demo : http://sachatrauwaen.github.io/simplealpacaformbuilder/formbuilder.html
Source code : https://github.com/sachatrauwaen/simplealpacaformbuilder

**Comment by jongarrison** [comment]
Very cool form builder demo!

**Comment by chunchill** [comment]
@sachatrauwaen  cool demo!
@jongarrison the dependency part dose answer my question!
