### ISSUE TITLE
Dependencies for form-builder is missing.

### ISSUE THREAD

**Issue by KBasher** [gitana/alpaca#404]
The form-builder.html file into the location https://github.com/gitana/alpaca/tree/master/site/demos/form-builder contains many js and css dependencies and the location is showing lib folder in root. But this folder does not contain those js and css files. That’s why the downloaded file is not functioning properly.
From where I can get those dependencies?

**Comment by uzquiano** [comment]
You need to run a build.  See the readme file for instructions on how to do so.

**Comment by KBasher** [comment]
Can I run a build on .net platform?
