### ISSUE TITLE
jquery price format no longer valid package

### ISSUE THREAD

**Issue by utilityboy** [gitana/alpaca#412]
Alpaca install fails with:

`bower jquery-price-format#2.0.0 ENORESTARGET No tag found that was able to satisfy 2.0.0`

I looked on bower and can find this package, but it doesn't resolve properly.  This was working until very recently so I'm not sure if the author changed his versioning mechanism.

**Comment by uzquiano** [comment]
Update the bower reference in head, thanks

**Comment by bertvh** [comment]
Is there any workaround for this issue? Or, will there be a new release quickly?

Thanks.

**Comment by uzquiano** [comment]
You can take a look at the checkin on head and adjust your bower JSON to do a local build on your own. 

It will be part of the next release as well. No plans around when yet. Your best option is to build alpaca on your own.
