### ISSUE TITLE
better widget for SelectField w/ multiple=true

### ISSUE THREAD

**Issue by JocelynDelalande** [gitana/alpaca#44]
The widget for multiple selection is the basic HTML one ([example](http://www.alpacajs.org/examples/components/fields/select-field.html#field4) )… Which is IMHO *the* widget in HTML history that no one understands nor wants to use.

**Comment by uzquiano** [comment]
Just closing this ticket out.  This one is very old but was also very useful and I appreciate everyone's input.  The JavaScript work moves at breakneck speed and about a year ago we went with bootstrap-multiselect.  So if anyone is looking for more advanced multiselect capabilities within the select control, you'll find it.  And that's the bad boy being used.
