### ISSUE TITLE
File upload error handling documentation is unclear/ inconsistent with implementation

### ISSUE THREAD

**Issue by Felttrip** [gitana/alpaca#455]
The documentation for the upload field states that you can set an optional `errorHandler` with the following description.  

> 	Optional function handler to be called when one or more files fails to upload. This function is responsible for parsing the underlying xHR request and populating the error message state.

Currently the behavior for `onUploadFail` is to send the data from the failed request to `errorHandler` which is line with the documentation. Unfortunately the default `errorHandler` function is expecting an array of strings to join together and alert with, not the request data. 

This pull request #454 has the simplest fix which is to have `onUploadFail` send the error in the format `errorHandler` is expecting. 

I think a more complete solution would be to update the default `errorHandler` function to do what the documentation describes. This would require updating [this](https://github.com/gitana/alpaca/blob/10d7da08e9e787430731d002ced455e0577aaf93/src/js/fields/advanced/UploadField.js#L466-L522) chunk of code to actually send an object to the default error handler in a format that is expected by it and to ignore #454 

I'd be willing to implement the fix but wanted to get an opinion from one of the maintainers before proceeding.

**Comment by jkernagis2** [comment]
+1

**Comment by LimeWub** [comment]
+1
lost a day over this

**Comment by Felttrip** [comment]
PR #454 was merged in so this should be a non issue now.
