### ISSUE TITLE
Totally unusable example form builder!

### ISSUE THREAD

**Issue by UralZima** [gitana/alpaca#473]
Hi. The form builder is totally unusable. I can't change code and see how it runs, if I add DATE field and modify it, all disappears. Order of radiobutton values not preserved. WTF is happening? And you offer THIS to PRODUCTION???

**Comment by uzquiano** [comment]
It's provided as an example.  Not as part of the Alpaca core.
It says so right on the top of the page.

I'm closing this as I don't appreciate your language or your attitude.  It's not productive and not at all in the spirit of open-source or the Alpaca community.

**Comment by UralZima** [comment]
I built latest master and it have same issues. I can't build any form with it. 
I built one and it showing warning for all required fields, I didn't even started to type

**Comment by UralZima** [comment]
Think about it. You loose reputation.
I tried latest master on chrome and firefox, bugs are same. The main bug is after modifying date field, all disappears or crashes.

**Comment by harrymoore** [comment]
@UralZima, As stated, that is sample code. feel free to fix any bugs to the sample and submit a pull request
