### ISSUE TITLE
Add 'main' field to package.json

### ISSUE THREAD

**Issue by ambischof** [gitana/alpaca#489]
For those of us using webpack, it would be great if `package.json` would include the 'main' field so that it can be used as the descriptor file instead of `bower.json`.

Some background to those not familiar, webpack will only look in one descriptor file, whichever it  finds first, and whichever is specified as the default is the same across all dependencies. Most packages are better off using `package.json` as the descriptor file but alpaca is the only dependency in my project which has both `package.json` and `bower.json` but has to use `bower.json`. 

This is only a one line change (and it is only proper node configuration) that would make many webpack users' lives a little easier.

**Comment by amkarlo** [comment]
I can't even get it to work with bower.json, that one line would really mean a lot!
