### ISSUE TITLE
Clear Validation

### ISSUE THREAD

**Issue by theleprechaun33** [gitana/alpaca#527]
Is there a way to clear the validation from the form? I am using the form in a popup window. When I initially open the form everything is fine. The process of closing the window triggers the validation if I don't enter any values in the required fields. So...when I click the button to re-open the form the validation is visible. I would like to be able to clear the values from the form (which I can do) and also clear the validation. I have tried form.topControl.refresh, which works, but when the form is launched after the refresh the first control doesn't focus and it looks like it has an additional border. Kind of strange. I really just want to be able to call a method and clear validation. I like the library a lot! Thanks.

**Comment by edneyego** [comment]
$('#ID').alpaca().refreshValidationState(true);
