### ISSUE TITLE
Please include the JSON for complex inline to make learning easier

### ISSUE THREAD

**Issue by ftrotter** [gitana/alpaca#53]
It is an awesome feature that you can import options, schema, etc from json files...

However, it means that in order to study the markup that created your complex forms, I have to manually load the json files to see what they contain.

**Comment by arthurportas** [comment]
Hi,
i do agree  provided interactive examples on http://www.alpacajs.org/examples.html should be improved, and your suggestion is valid. Let's see how can we contribute to make this better.
Cheers,
