### ISSUE TITLE
Interactive forms

### ISSUE THREAD

**Issue by kamov** [gitana/alpaca#547]
I would like to know if there is an example how to create interactive forms, where each fields appear one by one, something like typeform

Thanks

**Comment by MetaAbstract** [comment]
All examples are [here](http://www.alpacajs.org/examples.html)

**Comment by kamov** [comment]
Yes I see, but I don't see an example with interactive forms...

**Comment by MetaAbstract** [comment]
It's UI  genertor above json schema. So there are no interactive builder. You can find interactive builder for json schema, construct schema, load to alpaca and you will get the from.

**Comment by kamov** [comment]
I am not looking for interactive builder..
But interactive forms, forms with steps, where it's show one field at time.
Example like typeform: https://www.typeform.com/examples/forms/

**Comment by MetaAbstract** [comment]
Catch)...You can develop custom template for you form with events handlers.

**Comment by kamov** [comment]
Yes I see custom templates. But I guess how to show one field at time

**Comment by MetaAbstract** [comment]
you can make reverse engineering of typeforms in this behavior) or develop own solution for this task. In formal task is  show the part of the template with animation switching.

**Comment by ambischof** [comment]
You could probably achieve this with dependencies. Make each field dependent on the one before it having a value.

**Comment by kamov** [comment]
>You could probably achieve this with dependencies. Make each field dependent on the one before it having a value.

Sound good solutions. I will check into.  Thanks

**Comment by fosils** [comment]
@kamov I am interested in achieving the same, how did you do this in the end?

**Comment by kamov** [comment]
@fosils 

@ambischof give the solution:

"You could probably achieve this with dependencies. Make each field dependent on the one before it having a value."
