### ISSUE TITLE
date dropdown not working

### ISSUE THREAD

**Issue by ftrotter** [gitana/alpaca#55]
The following code displays a date field, and validates the field against the date format properly, but does not display the date dropdown icon.

I expect this is because I have not loaded some javascript, but I can find no mention on the date documentation page of any specific javascript library that must be preloaded...

{
    "schema": {
        "title": "FormTest form",
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "format": "string",
                "required": true
            },
            "test_date": {
                "type": "text",
                "format": "date",
                "required": true
            },
            "Address_id": {
                "type": "text",
                "format": "string",
                "required": true,
                "enum": [
                    11,
                    14,
                    52
                ],
                "default": "14"
            }
        }
    },
    "options": {
        "renderForm": true,
        "form": {
            "method": "post"
        },
        "buttons": {
            "submit": [

            ]
        },
        "fields": {
            "id": {
                "hidden": true,
                "label": "Id"
            },
            "test_date": {
                "label": "Test Date"
            },
            "Address_id": {
                "type": "select",
                "optionLabels": [
                    "Eleven",
                    "Fourteen",
                    "Fifty Two"
                ],
                "multiple": false,
                "label": "Address"
            }
        }
    },
    "data": {
        "id": 0
    }
}

**Comment by uzquiano** [comment]
Closing this out as the finer aspects of date handling were delegated to moment.js and we've also updated to newer datetime control libraries.  jQuery UI is no longer in the mix for the more advanced control types.
