### ISSUE TITLE
Alpaca Support for IOS

### ISSUE THREAD

**Issue by jp1993** [gitana/alpaca#552]
Our team using Alpaca Form Builder to generate dynamic form. 

I need to generate dynamic form in my iOS app in Swift from JSON which I receives from API response in Alpaca format i.e (Schema,Options,Data). So can you help me out that how can I generate form from JSON?

Is there any SDK or Framework provided by "Alpaca" or from any others by using it just by passing JSON I can be able to generate form. OR , Is there any other way to make it possible. Please let me know if it is possible.
I Attached the Screen Shot of JSON I received from API by using it I need to generate form.

![screen shot 2017-09-29 at 10 26 27 am](https://user-images.githubusercontent.com/11418918/31340378-9122a092-ad23-11e7-9ffe-55bed82cbe87.png)

**Comment by ambischof** [comment]
Use the Alpaca library directly. http://www.alpacajs.org/tutorial.html

**Comment by ambischof** [comment]
Sorry, I didn't realize you were using native iOS, I just assumed you were using something Cordova based.

As far as I know this is only for web.

**Comment by uzquiano** [comment]
Yes, Alpaca is for jQuery/Web.
