### ISSUE TITLE
Style customization for alpaca forms

### ISSUE THREAD

**Issue by brickcap** [gitana/alpaca#553]
Hello,

How can I customize the default button styles on the generated form? Is there an api for that or is it better to override the existing styles? I noticed that alpaca is using its own custom classes built on top of bootstrap. So I'm guessing those styles will need to be overridden. Can you please let me know what is the best way to go about this?

Thanks,
Akshat

**Comment by ambischof** [comment]
If I understand you correctly, you want to be able to change the classes, correct?

You need to override the view's styles: http://www.alpacajs.org/docs/api/views.html#toc_5

Here is the code that sets the default bootstrap-edit's button classes. https://github.com/gitana/alpaca/blob/master/src/js/views/bootstrap.js#L26

**Comment by brickcap** [comment]
Thanks @ambischof  View styles is exactly what I was looking for!
