### ISSUE TITLE
Mapping ISO8601 date representation in data to display pattern

### ISSUE THREAD

**Issue by tegebe** [gitana/alpaca#554]
I am missing documentation about how to map ISO8601 formatted date in data like

{"data": {"mydateproperty": "2017-10-11T10:45:00+01:00" }}

to a display value like "11.10.2017 10:45".

Can someone point me to the correct schema (and options) to archive this?

Regards,
Thilo

**Comment by ambischof** [comment]
Have you tried the option `dateFormat`?

**Comment by tegebe** [comment]
After several test it works when defining a picker in field options (even for readonly fields):
"picker": {
	  "format": "DD.MM.YYYY HH:mm",
	   "extraFormats": ["YYYY-MM-DDTHH:mm:ssZ"]
}

This only works with bootstrap not with jqueryui.
