### ISSUE TITLE
can I use Alpaca to make dynamic forms?

### ISSUE THREAD

**Issue by punto-** [gitana/alpaca#576]
Hi, I need to make a form where the user can add and remove different parts of it (for example add multiple addresses within the same form). Is this possible with Alpaca? I didn't see anything in the documentation, it looks like the entire form is created when I invoke the Alpaca method, but can I insert extra "chunks" into the form that's already created, or remove them? and later iterate through everything that was added for validation, etc?

Thanks!

**Comment by blakecodes** [comment]
You can possibly configure dynamic fields with their event handling.

http://www.alpacajs.org/docs/api/events.html

**Comment by punto-** [comment]
but that look like it works on fields that already exist, I need to create and delete parts of the form dynamically

**Comment by harrymoore** [comment]
Your example would work if you used an "array" in the schema definition: http://www.alpacajs.org/docs/fields/array.html

**Comment by Nj0376** [comment]
Yes use an array.  I use that and users can multiple addresses to the form.

**Comment by petri** [comment]
@punto if your question was answered, please close this issue.

**Comment by seanvree** [comment]
does anyone know how to POST the data in JSON array format when using this method?  All I get is "undefined"?
