### ISSUE TITLE
Creating an arbitrary button within a form?

### ISSUE THREAD

**Issue by roypardi** [gitana/alpaca#613]
_(this isn't really an "issue" but I've exhausted all other resources)_

I need to be able to add buttons *within* a form ( for `Electron` desktop app:  buttons to select files, pick directories, etc.). I've dug through all the documentation and searched through all the past issues, where I've seen similar needs posted but no real solutions.

I've tried adding a `<button>` to a template and ended up with the result in the image  below. That is not really a workable solution. I've seen some references in the "issues" about a "button" field type but I have not been able to get that to work.

I've posted [project code and details over on stackoverflow](https://stackoverflow.com/questions/49164240/does-alpacajs-have-a-button-type-how-can-i-create-a-button-anywhere) but `Alpacajs` doesn't seem a very active topic there. Does anyone have any suggestions or can give me a gentle shove in the ("a") right direction? I'm no Javascript/HTML hero but I can usually sort things out but this has me stumped.

----------
<img width="600" alt="screen shot 2018-03-07 at 8 39 08 pm" src="https://user-images.githubusercontent.com/9053196/37133304-7c685bda-2260-11e8-8c5c-2b3a978bacff.png">

**Comment by WhileTrueEndWhile** [comment]
You can find the template for a form element here: 
https://github.com/gitana/alpaca/blob/master/src/templates/web-edit/control.html
In your case, the property path is: `/path/projectPath`
Copy the template from above and paste it into your options as follows:
```
{
    ...
    "options": {
        "view": {
            "fields": {
                "/path/project/path": {
                    "templates": {
                        "control": `INSERT TEMPLATE HERE`
                    }
                }
            }
        }
    }
    ...
}
```
Please note the quotation marks.
Now you can insert the button into the template, but you are on your own when it comes to event handling...

**Comment by roypardi** [comment]
Thanks! That helped a lot
