### ISSUE TITLE
Auto Wizard loading URLs and Breaking Wizard

### ISSUE THREAD

**Issue by StephenOwens-dcat** [gitana/alpaca#62]
I have an instance of alpaca in which some of my data elements are URI based.  Apparently alpaca is attempting to load these URI's and throwing errors when they fail to load.  The data fields are supposed to be URI format, but not necessarily live links.  The wizard next button will not work as a consequence of these failures and it is impossible to fix the issues via the Alpaca generated wizard because the fields do not appear on the first step of the wizard.

**Comment by PratikshaAtDure** [comment]
Any one working on dependencies in alpaca wizard? I'm facing a default issue can any one help me out? Suppose a case where parent is a select menu with yes/no ; on selecting 'YES' child text box is shown which is required fields after touching the fields (error shown :This is a required field) npw user just updates the parent option to 'NO' keeping the previous page validation as it is. In this case next button does not allow to navigate to next step.

Thanks in advance,
Pratiksha
