### ISSUE TITLE
Array conditional dependencies not working in 1.5.24

### ISSUE THREAD

**Issue by Nj0376** [gitana/alpaca#632]
Hi,

In versions prior to 1.5.24 the following dependency code works.  If I select "Other" as the option then the dependent textbox appears in older version but does not in the current version.  If I change the type from array to string it works in 1.5.24, however for my backend system I need to have the array type working like it was previously.  Is this a known issue or is there an alternative way to have a dependency on an array type?

        $("#field1").alpaca({
            "schema": {
                "type": "object",
                "properties": {
                    "choice": {
                        "title": "Pick an option",
                        "type": "array",
                        "enum": ["OptionA","OptionB","Other"]
                    },
                    "other_option": {
                        "title": "Enter other option",
                        "type": "string",
                    },
                },
                "dependencies": {
                    "other_option": ["choice"]
                }
            },
            "options": {
                "fields": {
                    "choice": {
                        "type": "checkbox"
                    },
                    "other_option": {
                        "dependencies": {
                            "choice": "Other"
                        }
                    }
                }
            }
        });

**Comment by futon88** [comment]
I was having a similar issue.  Moving the enum to an 'items' element (with type string) solved it for me.  Essentially, example 7 on http://www.alpacajs.org/docs/fields/checkbox.html.

Try changing this:
~~~~
"choice": {
    "title": "Pick an option",
    "type": "array",
    "enum": ["OptionA","OptionB","Other"]
},
~~~~
to this:
~~~~
"choice": {
    "title": "Pick an option",
    "type": "array",
    "items": {        
        "type": "string",
        "enum": ["OptionA","OptionB","Other"]
    }
},
~~~~

**Comment by Nj0376** [comment]
That’s great. Should’ve thought of that. Thank you.
