### ISSUE TITLE
can i suspend "fires invalidation right away" on edit views?

### ISSUE THREAD

**Issue by rauwebieten** [gitana/alpaca#635]
Sometimes I want to show a form, and have some fields prepopulated, so I use the edit-view with a data-object.

However, I don't want to fire validation right away.
Is this possible? When I use the create-view, the data is not displayed.

**Comment by sebmill** [comment]
Have a look at the ``hideInitValidationError`` setting which can be applied at the very top level within your options, see this example here: https://jsfiddle.net/xpvt214o/176610/. If this answers your issue please mark it as closed.

**Comment by rauwebieten** [comment]
Yes, thank you !
