### ISSUE TITLE
Alpaca forms, one radio button per field

### ISSUE THREAD

**Issue by MrLeninstalock** [gitana/alpaca#638]
Hi guys !

I'm using Alpaca, and I'm having a problem.
I've got several field, pre-filled with JSON data. Some of thoses fields are on readOnly, so I can't modify them, BUT, I would like to have the possibility to "unlock" them and modify them. For this I would like to associate a radio button to each field, representing if the field is locked or not.
Problem is I got no idea how to associate a radio button to each field, and I don't even know if this is possible !

I hope that you guys, will be able to help me !:)

**Comment by sebmill** [comment]
You want to have a look at the [enable](https://github.com/gitana/alpaca/blob/1fd2cc7bfff3f151657edace6d49181e837b3795/src/js/ControlField.js#L607) / [disable](https://github.com/gitana/alpaca/blob/1fd2cc7bfff3f151657edace6d49181e837b3795/src/js/ControlField.js#L589)methods as well as the onChange [event handler](http://alpacajs.org/docs/api/events.html). I'm not sure if I understand your use case 100% but perhaps also read yourself into [abstracting your own Alpaca fields](http://alpacajs.org/docs/api/custom-fields.html), e.g. your own kind of text field which also renders the radio controls you need to enable/disable the actual input field.
Hope this helps.

**Comment by WhileTrueEndWhile** [comment]
The following issue may also help you:
https://github.com/gitana/alpaca/issues/613

Just add some HTML to the standard templates with possibly inline event handlers, which somehow get to the alpaca instance (`$(...).alpaca("get")`) and then manipulate it...

**Comment by MrLeninstalock** [comment]
Hi,

I've been able to make my field with a button at the end, using a template, but I'm confornted to another issue.
When I'm using form.getValue(), it does return original values, I mean, if I modify 1 field and then do a getValue(), the modification won't be visible.

I'm pretty sure there is a problem with my template but I can't figure what to do ! :(

Here is my templates code :

```
{% raw %}
<script type="text/x-handlebars-template" id="input-group-addon-template">
    <div class="input-group">
    <input type="{{inputType}}" value="{{data}}" id="{{id}}" {{#if options.placeholder}}placeholder="{{options.placeholder}}"{{/if}} {{#if options.size}}size="{{options.size}}"{{/if}} {{#if options.readonly}}readonly="readonly"{{/if}} {{#if name}}name="{{name}}"{{/if}} {{#each options.data}}data-{{@key}}="{{this}}"{{/each}} {{#each options.attributes}}{{@key}}="{{this}}"{{/each}}/>
        <div class="input-group-btn" id="{{id}}-basic-btn"> 
        <button class="btn btn-default" id="{{id}}-button" onclick="test(event)" >
            <i {{#if options.readonly}}class="fa fa-lock"{{else}}class="fa fa-unlock"{{/if}}></i> 
        </button>
       </div>
   </div>
</script>
{% endraw %}
<script> 
```

**Comment by WhileTrueEndWhile** [comment]
Is the test function called? Unfortunately, the implementation is not included. That should be like (assuming that a button has been added within a field template):
```
function test(event) {
    const button = $(event.target); // Get button
    const field = $(button).parent().parent() /*...*/; // Get corresponding field div
    const fieldId = $(field).data("alpaca-field-id"); // Get field Id
    const instance = Alpaca.fieldInstances[fieldId]; // Get instance
    instance.options.readonly = true; // Modify instance
    instance.refresh(); // Update instance
}
```
This is a concept and has not been tested...

**Comment by MrLeninstalock** [comment]
Yes the function is called and here is the function test :

```
function test(e) {
        e.preventDefault()
        console.log(e)
        button_class = e.originalTarget.children[0].className
        id = e.target.id
        field_id = id.replace("-button","")
        field_list.forEach(function(field) {
            if(field.id == field_id) {
                if(button_class=="fa fa-lock") { // We wan't to unlock the field
                    // Unlocking
                    field.options.readonly=false;
                    field.refresh()

                } else if(button_class == "fa fa-unlock") { //We wan't to lock the field
                    // When locking the field, we have to add the field to the modified_field
                    if(!modified_fields.includes(field.path)) {
                        modified_fields.push(field.path)
                    }
                    field.options.readonly=true;
                    field.refresh()
                    
                }
            }
            
        });
    }

```


Getting the field to be readOnly is working, there is no probs with that, but when it comes to retrieve its value, it doesn't work. It is always returning the original value, the one in the "data" ...

**Comment by MrLeninstalock** [comment]
Hi ! 

With some help, I've been able to get it to work. So I just had to modify the template, new template :

```
<script type="text/x-handlebars-template" id="input-group-addon-template">
    <div class="input-group">
        {{#control}}{{/control}}
        <div class="input-group-btn" id="{{id}}-basic-btn" > 
            <button class="btn btn-default" id="{{id}}-button" onclick="click_function(event)" >
                <i {{#if options.readonly}}class="fa fa-lock"{{else}}class="fa fa-unlock"{{/if}}></i> 
            </button>
        </div>
    </div>
</script>
```

So the big difference is that we don't precise the "input-type" anymore so that we don't override all usefull function as getValue etc.

I'll close this, but feel free to reopen if you get more explication or questions ! :)
