### ISSUE TITLE
datepicker options

### ISSUE THREAD

**Issue by ftrotter** [gitana/alpaca#64]
It is not clear, from the documentation, if it is possible to pass options along to the jquery datepicker system.

If it is possible, it should be included in the documentation.

If it is not possible, this is a fairly obvious feature...

http://api.jqueryui.com/datepicker/

Almost all of these should be useable via passthrough.. on one of the ways to turn these things on... 

It might be nice to have a syntax based on HTML5 date options... so that this would upgrade to HTML5 smoothly...

-FT

**Comment by PiQ99** [comment]
Hello,

my question is, how to apply options to the datepicker (bootstrap)? Actually it have to work with the "picker"-attribute in the options-properties, I already know, but I can not set a locale for the picker. 

Could you please help me?

**Comment by PiQ99** [comment]
Hey guys,

do you have any new ideas/functions/hints for me? The more the time runs, the more I would need an answer/workaround for this problem :-)

**Comment by ftrotter** [comment]
Closing given no updates.
