### ISSUE TITLE
Wysiwyg editor does not work

### ISSUE THREAD

**Issue by colegatron** [gitana/alpaca#66]
Using the current package, under Firefox 22.0 and Chrome 23.0.1271.97 (Build oficial 171054) . Not tested on other browsers or versions.

The Wysiwyg control does not work. It does not show the editor and the textbox is plain text.

I have tried the wysiwyg developer's library without alpaca (using the author website package) and it works correctly.

In my opinion it would be better for the framework to use a wider used editor (CKEditor or similar) and there are lots of plugins which can be used with.

**Comment by uzquiano** [comment]
Closing this one out as it's old at this point.  Alpaca now offers both CKEditor and TinyMCE fields as well as an ACE Cloud Editor field in addition to everything else.  We tossed out the old wysiwyg field many moons ago.  Thus, for anyone looking at this now, it'll be a very different situation.
