### ISSUE TITLE
Custom table validation

### ISSUE THREAD

**Issue by sorioli** [gitana/alpaca#671]
I've created a custom component extended from TableField and i've added to it 2 buttons that adds and remove rows and other code. When i add a new row, it happens that with that new row the table is invalid but the invalidation event is not called and the functions `isFormValid` or `isValid` keep return true. The only way to make the table fire the invalidation event is to change a value in the table (even with a valid one) to trigger the verification of validity of the table. I've tried calling `this.validate(true)` `this.form.validate(true)` or `this.form.refreshValidationState(true)` but nothing change, the table still valid even if it's not.
Any solution to this? Thanks.

**Comment by BrianH85** [comment]
By default the validation is only run when there is a change in the field to be validated. To run it manually you need to call "refreshValidationState()" like you mentioned.

I think I have a similar situation in my form where I refresh validation on a field when another changes:

`        "events": {
                            "change": function () {
                                this.getParent().childrenByPropertyId["critical"].refreshValidationState(true);
                            }`

Here this.getParent().childrenByPropertyId["critical"] is referencing the field I want to validate and refreshValidationState(true) refreshes it's validation state.

**Comment by sorioli** [comment]
I got it working using the callback of the function `refreshValidationState(validateChildren, cb)` and in the callback checking if the form is valid with `this.form.isFormValid()`. I also needed to trigger manually the event 'validated' or 'invalidated' of the main form, because it was not automatic fired.
