### ISSUE TITLE
accept attribute for file input

### ISSUE THREAD

**Issue by kelerago** [gitana/alpaca#674]
Hello.

It´s possible add attributes in inputs without "data-" prefix.?

this question it´s with the purpose to **add accept attribute** in file inputs.

**Comment by ambischof** [comment]
You can do so using the postRender function.

**Comment by teutates** [comment]
@ambischof How can someone add an accept attribute to a file using postRender? I have used postRender for many things but I do not believe this is possible. 

[`<input type="file" name="pic" accept="image/*">`](https://www.w3schools.com/tags/att_input_accept.asp)

**Comment by kelerago** [comment]
> You can do so using the postRender function.

Thank very much @ambischof . i've solved it using jquery directly without postRender function. But thanks for your interest.
