### ISSUE TITLE
Set Data Attributes for Select Field

### ISSUE THREAD

**Issue by aenany-atmosphereiot** [gitana/alpaca#679]
Dear Alpaca Team,

Thank you for developing this library, it has saved my team a ton of time building forms... I was wondering if you could include the option to insert data attributes for Select Fields, in a similar fashion to the TextFields, for example:

under alpaca.options.fields: 

```
firstName: {
    title: "First Name"
    type: "text",
    required: true,
    data: {
        example: 'dataExampleValue'
    }
}
```

I would also like this to be possible:

```
preference: {
    title: "Preference"
    type: "select",
    required: true,
    data: {
        example: 'dataExampleValue'
    }
}
```

Thank you so much.

**Comment by seseso** [comment]
You could edit the select template used by alpaca and add the same code as existing for text field:
{{#each options.data}}data-{{@key}}="{{this}}"{{/each}}

You can have a look in the Templates section of the Views page:
[http://alpacajs.org/docs/api/views.html](http://alpacajs.org/docs/api/views.html)
