### ISSUE TITLE
Implementing richer dependencies

### ISSUE THREAD

**Issue by codek** [gitana/alpaca#680]
We need to implement more interesting dependencies on the form, for example:

Another field is blank  (hence show/enable this one)  (Other field in this case is a text box, not a select)
Combinatorial syntax over several fields i.e. FieldA is blank, or not M, and Field B = null
Date calculations.  (display/enable fields only when a certain field is after a given date)

I'm thinking this can be achieved by binding to the change on the field and checking the other field values, before I do that is that the right approach?

**Comment by seseso** [comment]
I think you're in the right path. You can also have a look at the Observables:
[http://alpacajs.org/docs/api/observables.html](http://alpacajs.org/docs/api/observables.html)

**Comment by codek** [comment]
Thanks, I'll look at that.
