### ISSUE TITLE
Is there any way to specify the properties order?

### ISSUE THREAD

**Issue by Roger** [gitana/alpaca#71]
There's no way to ensure that the keys stay ordered when serializing/deserializing the object

**Comment by icenine457** [comment]
+1 - Also, if someone were to look into this, where would be a good place to start?

**Comment by uzquiano** [comment]
This has been fixed/improved using array sorting in the dev-1.5-futures branch.  It will be part of the next release or you can grab the branch, build it now and take a look at example 10 under the object field.

**Comment by uzquiano** [comment]
The order changes were merged back to master, so you can build from there.

**Comment by icenine457** [comment]
Thanks for the fast response! We're going to be using Alpaca a lot on our team, so it's awesome that this has been prioritized.
