### ISSUE TITLE
Is the hacked CDN fixed?

### ISSUE THREAD

**Issue by ObodoAssociates** [gitana/alpaca#733]
Hi,

I'm preparing to use Alpaca for the first time in a new project. In my research, I discovered that the alpaca.js CDN was hacked. Has this issue been resolved permanently? They mention that the CDN was taken down in [this article](https://www.scmagazine.com/home/security-news/sites-infected-as-open-source-alpaca-forms-and-analytics-service-picreel-compromised/), but I couldn't find anything else about a permanent resolution anywhere.

Thanks!

**Comment by uzquiano** [comment]
Yes. That occurred earlier this year where some versions of the alpaca min files were affected. The issue was addressed immediately.

Check the docs as all the CDN hosted files are now provided by jsDeliver.

I’ll close this as there are no further actions here.

Michael

**Comment by ObodoAssociates** [comment]
Thanks for the quick response @uzquiano!

Looking forward to getting started.
