### ISSUE TITLE
Error for VIEW_MOBILE_DISPLAY

### ISSUE THREAD

**Issue by critical** [gitana/alpaca#75]
I'm using alpacajs with jquerymobile and I have the following form where data contains values for only required fields. 

$("#form").alpaca({
"data" : data,
"schema" : schema,
"options" : options,
"postRender" : postRenderCallback,
"view" : "VIEW_MOBILE_DISPLAY"
});

When I use "VIEW_MOBILE_DISPLAY" to execute a "display only" of form I get this exception:
"Uncaught Error: Runtime view for view id: [object Object] could not find a normalized view ".
Can you help me?
Thanks in advance

**Comment by uzquiano** [comment]
This one is pretty old and wasn't addressed.  I suspect the reason is that we need a working example to test against.  Please supply a fiddle if you can of something working where we can quickly see the error reproduced.  Cheers!
