### ISSUE TITLE
remote options "optionsSource" and event handlers

### ISSUE THREAD

**Issue by chrisben** [gitana/alpaca#83]
optionsSource points to a .json file that contain options.

How does it replace javascript defined options when there are event handler functions defined there?

For instance (taken from one of the example on the site):
```javascript
"options": {
            "items": {
                "extraToolbarButtons": [{
                    "feature": "clear",
                    "icon": "ui-icon-cancel",
                    "label": "Clear inputs",
                    "clickCallback": function(id, arrayField) {
                        var item = arrayField.childrenById[id];
                        $(item.field).val('');
                    }
                }]
            }
        }
```

How do you declare that javascript function definition ("clickCallback") in a json file? (this is not valid json if stored as-is).

Also is it possible to mix remote options ('optionsSource') and just 'options' : will it merge them?

**Comment by uzquiano** [comment]
This is implemented in head.  Will be part of the 1.5.9 release.
